--- # AGSImager menu
- About:
  - rank: 1
  - note: "            AmigaVision 2025.05.05          
  The Ultimate Amiga Game & Demo Scene Setup 

       By Alex Limi & David Lindecrantz      
   Aka. LIMI of Offence & Optiroc of Megaboys
     Artwork by PAL of Offence & Optiroc     
   Launcher by Magervalp, Optiroc, StatMat   
        Support your local demo scene!        "
  - Nothing to see here:
    - rank: 1
    - note: Intentionally left blank.
  - AmigaDealerDemo

- !include Lists/Games-HallOfFame.yaml
- !include Lists/Games-Charts.yaml
- !include Lists/Games-Curated.yaml
- !include Lists/Games-Decennial.yaml
- !include Lists/Games-Focus.yaml
- !include Lists/Games-Gameographies.yaml
- !include Lists/Games-Multiplayer.yaml
- !include Lists/Games-SpecialHardware.yaml

- "[ Demo Scene ]":
  - note: A sample of demo scene releases.
  - !include Lists/Demos.yaml
  - !include Lists/Demos-Spotlight.yaml
  - Widescreen: !include Lists/Demos-Widescreen.yaml
