--- # AGSImager menu
- About:
  - rank: 1
  - note: "MEGA AGS POCKET LiTE 2023.05.XX"
  - Nothing to see here:
    - rank: 1
    - note: Intentionally left blank.
  - AmigaDealerDemo

- !include Lists/Games.yaml

- "[ Demo Scene ]":
  - note: A sample of demo scene releases.
  - !include Lists/Demos.yaml
