--- # AGS2 Menu structure
- Test:
  - CrystalDragon # Installer seems bodged now, it used to work fine.
  - GhoulsNGhosts # This seems to work great in NTSC, but I can't make the offset stick to push it up. Leaving here, so we can experiment.
  - LethalXcess # Works great in NTSC (and more playable, shoot'em-up), but needs alignment
  - Oath # PAL60, but need to find a way to offset, too far down
  - Turrican3 # Should be PAL5, but I can't get it to "stick"?
  - WindowWizard # Loads a screen with some pixels in the middle, then stops
