--- # AGS2 Menu structure
- Test:
  - AnotherWorldLostLevel # PAL (but can't get past copy protection?)

  - CannonFodder # Need to double check these against CannonSoccer
  - CannonFodder2
  - CannonFodder2AlienLevels
  - CannonFodderCD32
  - CannonFodderNewCampaign
  - CannonFodderPlus

  - CrystalDragon # Installer seems bodged now, it used to work fine.

  - Fascination # Can't seem to get past the copy protection

  - GhoulsNGhosts # This seems to work great in NTSC, but I can't make the offset stick to push it up. Leaving here, so we can experiment.
  - GreatCourts # Not on my image

  - LandGenesis
  - Leander
  - LEDStorm
  - LemmingsHoliday1993
  - LemmingsHoliday1994
  - LemmingsNewYear9192
  - LemmingsXmasDemo1991
  - LemmingsXmasDemo1992
  - LethalXcess
  - Lionheart
  - LiquidKids
  - Llamatron
  - Logical
  - Logistic
  - Lorna
  - LostPatrol
  - Lotus
  - Lotus2
  - Lotus3

  - MagiclandDizzy
  - MagicPockets
  - Masterblazer
  - Maya
  - MegaLoMania
  - MegaTyphoon
  - Menace
  - MetalLaw
  - MetalMutant
  - MFTanks
  - MidnightResistance
  - MiG29Fulcrum
  - MightyBombJack
  - MontyPythonsFlyCir
  - Moonstone
  - MrNutz
  - MUDS

  - Narc
  - NarcoPolice
  - NathanNever
  - Nebulus2
  - NeverMind
  - NewZealandStory
  - NightShift
  - NinjaWarriors
  - Nitro
  - NorthAndSouth
  - NoSecondPrize

  - Oath
  - Obsession
  - Odyssey
  - OffShoreWarrior
  - OneStepBeyond
  - OperationThunderbolt
  - OperationWolf
  - Oxxonian

  - Pang
  - Paradroid90
  - ParasolStars
  - PersonalNightmare
  - PGATourGolf
  - PinballDreams
  - PinballFntsies
  - PinballIllusions
  - PinballPrelude
  - PlayerManager
  - PlayerManager2
  - PlayerManager2ExtraAGA
  - Pod
  - Poing
  - Poing2
  - Poing3
  - Poing4
  - Poing5
  - Poing6
  - Poing7
  - Populous&DataDisks
  - PostmanPat
  - PowermongerWW1Edition
  - Premiere
  - ProjectXSE
  - ProjectXSE2017
  - ProTennisTour
  - ProTennisTour2
  - Psyborg
  - PuffysSaga
  - Puggsy
  - PushOver
  - Putty
  - PuttySquad

  - Skidmarks # Launches a weird dial-up thing?
  - SuperGridRunner # Not on the image?

  - TFX # Not on the image?
  - Turrican3 # Should be PAL5, but I can't get it to "stick"?

  - WindowWizard # Loads a screen with some pixels in the middle, then stops
