--- # AGS2 Menu structure
- Test:
  - game--arabiannights--arabiannights
  - game--awesome--awesome
  - game--batmanthemovie2disk--batmanthemovie2disk
  - game--blastar--blastar
  - game--bonecruncher--bonecruncher
  - game--bonecruncherenhanced--bonecruncherenhanced
  - game--crystaldragon--crystaldragon # still doesn't launch
  - game--dangerfreak--dangerfreak # Lots of gfx corruption
  - game--fireandicecd32--fireandicecd32  
  - game--fire&icexmasdemo--fire&icexmasdemo
  - game--flashback--flashback
  - game--international3dtennis--international3dtennis
  - game--internationaltennis--internationaltennis
  - game--jimpower--jimpower
  - game--katakis2disk--katakis2disk # Never gets past asking for data disk
  - game--kidchaos--kidchaos
  - game--landgenesisagacd--landgenesisagacd

  - game--magicpockets--magicpockets
  - game--masterblazer--masterblazer
  - game--megalomania--megalomania
  - game--megatyphoon--megatyphoon
  - game--menace--menace
  - game--metalmutant--metalmutant
  - game--midnightresistance--midnightresistance
  - game--mightybombjack--mightybombjack
  - game--montypythonsflycir--montypythonsflycir
  - game--moonstone--moonstone
  - game--mrnutz--mrnutz
  - game--muds--muds
  - game--narc--narc
  - game--narcopolice--narcopolice
  - game--nathanneverit--nathanneverit
  - game--nebulus2--nebulus2
  - game--nevermind--nevermind
  - game--newzealandstory--newzealandstory
  - game--nightshift--nightshift
  - game--ninjawarriors--ninjawarriors
  - game--nitro--nitro
  - game--northandsouthimage--northandsouthimage
  - game--nosecondprize--nosecondprize
  - game--odyssey--odyssey
  - game--offshorewarrior--offshorewarrior
  - game--onestepbeyond--onestepbeyond
  - game--operationthunderbolt--operationthunderbolt
  - game--operationwolf--operationwolf
  - game--pang--pang
  - game--panzakickboxing--panzakickboxing
  - game--paradroid901mb--paradroid901mb
  - game--parasolstars--parasolstars
  - game--persiangulfinferno--persiangulfinferno
  - game--pgatourgolf&tourdisk--pgatourgolf&tourdisk
  - game--playermanager--playermanager
  - game--populous&datadisks--populous&datadisks
  - game--populous&datadisks--populous&datadisks--tff
  - game--populous&datadisks--populous&datadisks--tpl
  - game--populousworldeditor--populousworldeditor
  - game--postmanpat--postmanpat
  - game--protennistour--protennistour
  - game--protennistour2--protennistour2
  - game--psyborg--psyborg
  - game--puggsy--puggsy
  - game--pushover--pushover
  - game--putty--putty
  - game--puttysquadaga--puttysquadaga
  - game--quartz--quartz
  - game--qwak--qwak
  - game--rainbowislands--rainbowislands
  - game--rallycrosschallenge--rallycrosschallenge
  - game--rbi2baseball--rbi2baseball
  - game--redheat--redheat
  - game--rickdangerous--rickdangerous
  - game--rickdangerous2--rickdangerous2
  - game--rickdangerous25--rickdangerous25
  - game--ringsofmedusa--ringsofmedusa
  - game--roadkillaga--roadkillaga
  - game--robinhoodlegendquest--robinhoodlegendquest
  - game--robocop--robocop
  - game--robocop3--robocop3
  - game--rocknroll--rocknroll
  - game--rockstaratemyhamster--rockstaratemyhamster
  - game--rodland--rodland
  - game--rtype2--rtype2
  - game--ruffntumble--ruffntumble
  - game--rygaraga--rygaraga
  - game--saintdragon--saintdragon
  - game--sarcophaser--sarcophaser
  - game--scoobydoo&scrappydoo--scoobydoo&scrappydoo
  - game--secondsamuraiaga--secondsamuraiaga
  - game--sevengatesofjambalaimage--sevengatesofjambalaimage
  - game--shadowlands--shadowlands
  - game--shadowofthebeast--shadowofthebeast
  - game--shadowofthebeast2--shadowofthebeast2
  - game--shadowofthebeast3--shadowofthebeast3
  - game--shadowwarriors--shadowwarriors
  - game--silkworm--silkworm
  - game--simonthesorcereraga--simonthesorcereraga
  - game--simulcra--simulcra
  - game--skidmarksaga--skidmarksaga
  - game--sleepwalkeraga--sleepwalkeraga
  - game--snowbrosimage--snowbrosimage
  - game--soccerkidaga--soccerkidaga
  - game--spaceharrier2--spaceharrier2
  - game--speedball2--speedball2
  - game--storiaancestrale--storiaancestrale
  - game--storiaancestrale--storiaancestrale--ch2
  - game--storiaancestrale--storiaancestrale--ch3
  - game--storiaancestrale--storiaancestrale--ch4
  - game--stuntcarracer--stuntcarracer
  - game--stuntcarracertnt--stuntcarracertnt
  - game--supercars2--supercars2
  - game--supercars2disk--supercars2disk
  - game--superherodemo--superherodemo
  - game--supersillyskidmarkscd--supersillyskidmarkscd
  - game--superskidmarks--superskidmarks
  - game--superskidmarks+cd--superskidmarks+cd
  - game--superskidmarksfyedcd--superskidmarksfyedcd
  - game--superstardustaga--superstardustaga
  - game--switchblade--switchblade
  - game--switchblade2--switchblade2
  - game--tensaidemo--tensaidemo
  - game--tfxaga--tfxaga
  - game--thunderhawkah73m--thunderhawkah73m
  - game--tinybobble--tinybobble
  - game--tinytroops--tinytroops
  - game--toki--toki
  - game--tony&friends--tony&friends
  - game--toobin--toobin
  - game--torvakthewarrior--torvakthewarrior
  - game--trapsntreasures--trapsntreasures
  - game--turrican--turrican
  - game--turrican2--turrican2
  - game--turrican3--turrican3
  - game--tusker--tusker
  - game--ufoenemyunknown--ufoenemyunknown
  - game--universe--universe
  - game--unrealntsc--unrealntsc
  - game--untouchables--untouchables
  - game--untouchablesse--untouchablesse
  - game--vaxine--vaxine
  - game--virocopaga--virocopaga
  - game--voyager--voyager
  - game--vroom&datadisk--datadisk
  - game--vroom&datadisk--vroom
  - game--vroommultiplayer--vroommultiplayer
  - game--walkerdecrunched--walkerdecrunched
  - game--warhead--warhead
  - game--warzonecoredesign--warzonecoredesign
  - game--warzoneparadox--warzoneparadox
  - game--waxworks--waxworks
  - game--westerngames--westerngames
  - game--wolfchild--wolfchild
  - game--worms2mb--worms2mb
  - game--wormsdcaga12mb--wormsdcaga12mb
  - game--yolandaimage--yolandaimage
  - game--zarathrusta--zarathrusta
  - game--zeewolf--zeewolf
  - game--zeewolf2--zeewolf2
  - game--zout--zout
  - game-notwhdl--brutalhomicide
  - game-notwhdl--poing
  - game-notwhdl--poing2
  - game-notwhdl--poing3
  - game-notwhdl--poing4
  - game-notwhdl--poing5
  - game-notwhdl--poing6
  - game-notwhdl--poing7
