--- # AGS2 Menu structure
- Test:
  - Jormas-MeganeRellu

- '[ Demo Scene ]':
  - note: A sample of demo scene releases.
  - Favorites:
    - note: Awesome or somehow significant releases according to 1.000.000 BOYS aka Megaboys.
    - 15YearsOfFame
    - 3DDemo2
    - Abyss-Coda
    - Arte
    - BatmanVuelve
    - BaygonAGA
    - BrunosMusicBox3
    - Coma
    - CopperMaster
    - Darkroom
    - DayOfReckoning
    - DesertDream
    - Drugstore
    - EndlessPiracy-Scrabble
    - Enigma
    - Extension
    - FridayAtEightAGA
    - FullmoonAGA
    - HapyCarva72
    - Hardwired
    - HisMastersNoise
    - How2SkinACat
    - HumanTarget
    - Interference
    - Interparallactic
    - InTheKitchen
    - JesusOnEs
    - Joyride
    - KanaalinarVoitus
    - KayraSoiro
    - Lemon-Colombia
    - LostWorld
    - MajorRelease
    - MaximumVelocity
    - Megademo2Rebels
    - MegademoAvenger
    - MegademoBeastieBoys
    - MegademoBudbrain
    - MegademoDeathstar
    - MegademoJoy&MGF&TJC
    - MegademoNorthStar
    - Megademo3NSFLT
    - MegademoRedSectorInc
    - MegademoRoyalAmigaForce
    - MeganeRellu
    - Melon-Tetris
    - MentalHangover
    - MonoMeno66
    - MusicDisk3DMob
    - Nexus7AGA
    - NumbAGA
    - Paranoimia-AnotherCrack
    - Paranoimia-Turicon
    - Paranoimia-XOut
    - PlanetMAGA
    - PlasticPassion
    - RedSector-Plutos
    - RinkADinkRedux
    - Roots2AGA
    - Sequential
    - ShinobiIntro
    - SOS--SOS
    - Spaceballs-Emperor
    - Spaceballs-Makt
    - [Spaceballs-Peek, "3D glasses (red-blue) recommended!"]
    - Stateline
    - Stellar-Bananamen
    - TechnologicalDeath
    - TechTech
    - TerminalFuckup
    - UnitA FA18Interceptor
    - WorldOfCommodore
