--- # AGS2 Menu structure
- Test:
  - CrystalDragon # Installer seems bodged now, it used to work fine.

  - FormulaOneGrandPrix4Disk
  - Frenetic
  - Frontier
  - FutureTank
  - FutureWars
  - Fuzzball

  - GalacticTheXmasEdition
  - Gauntlet3
  - GemX
  - GhoulsNGhosts
  - Globdule
  - Goal
  - Gods
  - GoldenAxe
  - GoofysRailwayExpress
  - GrandMonsterSlam
  - Gunship2000

  - HardNHeavy
  - Harlequin
  - HelterSkelter
  - HeroQuest
  - HeroQuest2
  - HexumaDe
  - Hillsfar
  - HiredGuns
  - Historyline
  - Historyline--Intro
  - HollywoodPokerPro
  - Hostages
  - HudsonHawk
  - Hunter
  - Hybris

  - IK+
  - Impossamole
  - ImpossibleMission2025
  - IndianaJonesAtlantisAdv
  - Indianapolis500
  - IndyHeat
  - IndyJonesLastCrusAdv
  - InnocentUntilCaught
  - InsectsInSpace
  - International3DTennis
  - Interphase
  - Ivanhoe

  - JaguarXJ220
  - JamesPond
  - JamesPond2
  - JamesPond3
  - JimmyWhitesSnooker
  - JimPower
  - JudgeDredd
  - JungleStrike
  - K240
  - Katakis
  - KickOff2
  - KidChaos
  - KidGloves
  - Kikstart2
  - KillingGameShow
  - KingOfChicago
  - Klax
  - KnightsOfTheCrystallion
  - Kristal
  - Kult

  - LamborghiniAmericanChllng
  - LandGenesis
  - Larrie
  - LaserSquad
  - Leander
  - LEDStorm
  - LegendOfKyrandia
  - LeisureSuitLarry3
  - Lemmings
  - Lemmings2
  - LightCorridor
  - Lionheart
  - LiquidKids
  - Llamatron
  - Logical
  - Logistic
  - Loom
  - Lorna
  - LostPatrol
  - LostTreasuresOfInfocom
  - LostVikings
  - Lotus
  - Lotus2
  - Lotus3

  - MagicPockets
  - ManiacMansion
  - Masterblazer
  - Maya
  - MegaLoMania
  - MegaTyphoon
  - Menace
  - Mercenary
  - Mercenary3
  - MetalLaw
  - MetalMutant
  - MFTanks
  - MidnightResistance
  - Midwinter
  - MiG29Fulcrum
  - MightyBombJack
  - MindWalker
  - MonkeyIsland2
  - MontyPythonsFlyCir
  - Moonstone

  - MrNutz
  - MUDS
  - Murder
  - Narc
  - NarcoPolice
  - NathanNever
  - NaughtyOnes
  - Nebulus
  - Neuromancer
  - NeverMind
  - NewZealandStory
  - NightShift
  - NinjaWarriors
  - Nitro
  - NorthAndSouth
  - NoSecondPrize
  - NuclearWar

  - Oath
  - Obsession
  - OhNoMoreLemmings
  - OilImperium
  - OneStepBeyond
  - OperationCleanstreets
  - OperationStealth
  - Oxxonian

  - Pacmania
  - Pang
  - PanzaKickBoxing
  - Paradroid90
  - ParaglidingSimulation
  - ParasolStars
  - Perihelion
  - PersonalNightmare
  - PGAEuropeanTour
  - PGATourGolf
  - Phantasie3
  - PinballDreams
  - PinballFntsies
  - PinballIllusions
  - PinballPrelude
  - PioneerPlague
  - PipeDream
  - Pirates
  - Plotting
  - Pod
  - Populous
  - Populous2&ChallengeGames
  - PortsOfCall
  - Powermonger
  - Premiere
  - PrinceOfPersia
  - Project1
  - Projectyle
  - ProTennisTour
  - ProTennisTour2
  - Psyborg
  - Puggsy
  - PurpleSaturnDay
  - PushOver
  - Putty
  - PuttySquad
  - Puzznic

  - Qix
  - Quartz
  - Questron2

  - Racter
  - RailroadTycoon
  - RainbowIslands
  - Rampart
  - RanX
  - RBI2Baseball
  - Realms
  - RedHeat
  - RedStormRising
  - Renegade
  - Resolution101
  - RevengeOfMutantCamels
  - RevengeOfMutantCamels2
  - RickDangerous
  - RickDangerous2
  - RiseOfTheDragon
  - Roadkill
  - RoadwarEuropa
  - RoboCop
  - RoboCop3
  - RocketRanger
  - RockNRoll
  - RodLand
  - Rogue
  - RType
  - RuffNTumble
  - RygarAGA

  - SaintDragon
  - Sarcophaser
  - ScoobyDoo&ScrappyDoo
  - SecondSamurai
  - SecretOfMonkeyIsland
  - Sentinel
  - Settlers
  - ShadowFighter
  - Shadowlands
  - ShadowOfTheBeast
  - ShadowOfTheBeast2
  - ShadowOfTheBeast3
  - ShadowWarriors
  - Shanghai
  - ShaqFu
  - ShockWave
  - ShufflepuckCafe
  - Silkworm
  - SillyPutty
  - SimCity
  - Simulcra
  - Sinbad
  - Skidmarks
  - SlamTilt
  - SlySpySecretAgent
  - SnowBros
  - SoccerKid
  - Spaceball
  - SpaceHarrier2
  - Spaceport
  - SpaceTaxi3
  - Speedball
  - Speedball2
  - SperisLegacy
  - SpindizzyWorlds
  - Springtime
  - Starblaze
  - Starglider
  - Starglider2
  - Statix
  - StuntCarRacer
  - SuperCars
  - SuperCars2
  - SuperGridRunner
  - SuperHangOn
  - SuperHero
  - SuperOffRoad
  - SuperScrambleSimulator
  - SuperSkidmarks+CD
  - SuperSkweek
  - SuperStardust
  - SuperTwintris
  - SuprTennisChmps
  - Switchblade
  - Switchblade2
  - SWIV
  - SwordOfSodan
  - Syndicate

  - TempleOfApshaiTrilogy
  - Tensai
  - TestDrive2
  - TetrisMirrorsoft
  - TetrisPro
  - TFX
  - TheirFinestHour
  - ThemePark
  - ThunderHawkAH73M
  - TinyTroops
  - TitusTheFox
  - Toki
  - TomAndTheGhost
  - Tony&Friends
  - Toobin
  - TorvakTheWarrior
  - TotalEclipse
  - TotalRecall
  - TowerOfBabel
  - TowerOfBabel
  - TrapsNTreasures
  - TreasureTrap
  - TrexWarrior
  - Turrican
  - Turrican2
  - Turrican3
  - TVSportsFootball
  - Twintris
  - TwinWorld
  - TyphoonThompson

  - Ugh
  - Ultima5
  - Universe
  - Unreal
  - Untouchables
  - Uridium2
  - Vaxine
  - VenusTheFlytrap
  - Virocop
  - Virus
  - Voyager
  - Vroom

  - Walker
  - Warhead
  - WarzoneCoreDesign
  - Waxworks
  - WCLeaderBoard
  - WeirdDreams
  - WesternGames
  - WIEuropeIsCarmenSandiego
  - WindowWizard
  - Wings
  - WingsOfFury
  - WITUSAIsCarmenSandiego
  - WITWIsCarmenSandiego
  - Wizball
  - Wizkid
  - WizNLiz
  - Wolfchild
  - WorldGames
  - Worms
  - WormsDC

  - Xenon
  - Xenon2
  - XOut
  - Xybots
  - YoJoe
  - Yolanda
  - ZanyGolf
  - Zarathrusta
  - Zeewolf
  - Zool
  - ZOut
