--- # AGS2 Menu structure
- Done:
  - 3001OConnorsFight
  - 3DGalax
 
  - ActionFighter
  - AddamsFamily
  - AdventuresOfQuik&Silva
  - AgonyNTSC
  - AirborneRanger # NTSC
  - AirSupportNTSC
  - Akira
  - Alcatraz
  - Alianator
  - AlienBreed
  - AlienBreed2AGA
  - AlienBreedSpecialEdition
  - AlienBreedTA # PAL
  - AlienDrugLords
  - AllNewWorldOfLemmingsAGA
  - AllTerrainRacing
  - AlphaWaves
  - AlteredDestiny
  - Ambermoon
  - Amegas
  - Amiganoid
  - Amnios
  - AnotherWorld # 2 PAL5
  - AnotherWorldLostLevel # 2 PAL5
  - APBImage # PAL
  - ApidyaKaiko
  - ApidyaSpecialEdition # PAL
  - Apprentice
  - AquaticGames
  - AquaventuraNTSC
  - ArabianNights
  - ArcadePoolAGA
  - ArcherMacLeansPool
  - ArchipelagosNTSC
  - ArkanoidNTSC
  - ArkanoidRevengeOfDoh
  - Assassin
  - AssassinSpecialEdition
  - Astaroth # 1 PAL5 (Music is too fast if not)
  - ATF2
  - AtominoNTSC
  - Atomix # PAL
  - Awesome
  - AxelsMagicHammer

  - BadCat
  - BadCompany
  - BadLands
  - BalanceOfPower1990Ed
  - Ballistix
  - Banshee
  - Barbarian2Palace 
  - BaseJumpers
  - BatmanCapedCrusader
  - BatmanTheMovie
  - BattleChess # NTSC
  - BattleChess2 # NTSC
  - BattleCommand
  - BattleIsle
  - BattleSquadronNTSC
  - Battletech
  - BCKid
  - BeachVolley
  - BeneathAStlSky
  - Benefactor
  - BestOfTheBest
  - BeyondTheIcePalace # PAL60
  - BigRun
  - BillsTomatoGameNTSC
  - BioChallenge
  - BionicCommando
  - BiplaneDuel # 12 PAL5
  - BlackCrypt
  - BladeWarrior
  - Blastar
  - Blasteroids
  - Blob
  - BloodMoney
  - BloodNet
  - BMXSimulator # PAL60
  - Bobo
  - BodyBlows
  - BombJack
  - Bombuzal
  - BoneCruncherEnhanced # 7 PAL5
  - Botics
  - BrandsHatch
  - BrianTheLion
  - BrutalHomicide # PAL
  - BrutalHomicide2 # PAL
  - BubbaNStix
  - BubbleAndSqueak # PAL
  - BubbleBobble
  - Budokan
  - BuggyBoy
  - Builderland
  - BundesligaMngrHatt

  - Cabal
  - Cadaver
  - CadaverThePayoff # 0 PAL5
  - CaliforniaGames
  - CannonFodder # 11 PAL5
  - CannonFodder2 # 11 PAL5
  - CannonFodder2AlienLevels # 11 PAL5
  - CannonFodderCD32 # 11 PAL5
  - CannonFodderNewCampaign # 11 PAL5
  - CannonFodderPlus # 11 PAL5
  - CannonSoccer # 11 PAL5
  - Captive
  - CardiaxxTeam17
  - CaribbeanDisasterDe
  - CarlLewisChallenge
  - Carnage
  - CarrierCommand
  - CarVup
  - CastleMaster
  - CastleMaster2
  - CastleWarrior
  - CelticLegends
  - Centurion
  - ChambersOfShaolin # 7 PAL5
  - ChaosEngine
  - ChaosEngine2
  - ChuckRock # -5 PAL5
  - ChuckRock2 # 5 PAL5
  - CircusAttractions
  - Civilization
  - Civilization # NTSC
  - ClikClak
  - ClownOMania # PAL
  - Colonization # NTSC
  - Colony
  - CrazySue
  - CrazySueGoesOn
  - CruiseForACorpse
  - CrystalHammerV2
  - CrystalKingdomDizzy # PAL
  - Cubulus # PAL60
  - CurseOfEnchantia
  - Cybercon3
  - Cyberpunks
  - Cytron

  - Damocles
  - Darkmere
  - DarkSeed
  - DarkSeedCD32
  - Datastorm
  - DeathSword # PAL60
  - Defender2
  - DefenderOfTheCrown
  - Deflektor
  - DejaVu
  - DejaVu2LostInLasVegas
  - Denaris
  - DesertStrike
  - Deuteros
  - DeviousDesigns
  - DGeneration
  - DisposableHero
  - DistantArmies
  - DizzyCollection--Disk1 # PAL
  - DizzyCollection--Disk2 # PAL
  - DizzysExcellentAdventures--Disk1 # PAL
  - DizzysExcellentAdventures--Disk2 # PAL
  - DogsOfWar
  - DojoDan
  - DownhillChallenge
  - DragonBreed
  - DragonStrike
  - DreamWeb
  - DrivinForce
  - DuckTales # NTSC
  - Dune # 20 PAL5
  - Dune2
  - DungeonMaster
  - DynaBlaster
  - Dyter07

  - Ebonstar
  - Eco
  - Elfmania
  - Elite
  - Elvira
  - Elvira2
  - EmeraldMine # 1 PAL5
  - EmeraldMine2 # 1 PAL5
  - EmeraldMine3 # 1 PAL5
  - EMotion
  - EMotion # 6 PAL5
  - EmpireSoccer94
  - EmpireStrikesBack
  - Epic
  - EscapeFTPOTRobotMonsters
  - Extase
  - Exterminator
  - EyeOfTheBeholder
  - EyeOfTheBeholder2
  - EyeOfTheBeholder2AGA
  - EyeOfTheBeholderAGA

  - F15StrikeEagle2
  - F19StealthFighter
  - F29Retaliator
  - FA18Interceptor
  - FaeryTaleAdventure # PAL60
  - Falcon
  - FantasticDizzy # 12 PAL5
  - FantasyWorldDizzy # 23 PAL5
  - Fascination # 24 PAL5
  - FateGatesOfDawn
  - FernandezMustDie # PAL60
  - FinalAssault # NTSC
  - FinalBlow
  - FinalCountdown
  - FireAndBrimstone
  - FireAndIce
  - FireForce # PAL60
  - Firepower # NTSC
  - FirstContact # PAL60
  - FirstSamurai
  - Flashback
  - FlightOfTheAmazonQueen
  - Flink # PAL60
  - Flood
  - Floor13
  - FlyHarder # PAL60
  - FlyingSharkSE # PAL60
  - FormulaOneGrandPrix4Disk # NTSC
  - FourCrystalsOfTrazere
  - Frenetic # 23 PAL5
  - Frontier # PAL60
  - FrontierCD32
  - FuryOfTheFurries # PAL60
  - FuryOfTheFurriesCD32 # PAL60
  - FutureTank # PAL60
  - FutureWars # 6 PAL5
  - Fuzzball # PAL

  - GalacticTheXmasEdition # PAL
  - Gauntlet2 # NTSC
  - Gauntlet3 # PAL60
  - GemX # PAL
  - Giana2 # PAL60
  - Giganoid # PAL60
  - Globdule # 8 PAL5
  - Goal # 30 PAL5
  - Gobliiins # PAL60
  - Gobliins2 # PAL60
  - Goblins3 # PAL60
  - Gods # 14 PAL5
  - GoldenAxe # NTSC
  - GoofysRailwayExpress # 18 PAL5
  - GreatCourts2 # 10 PAL5
  - GrandMonsterSlam # PAL
  - Gravity # PAL60
  - GreatGianaSisters # PAL60
  - Gunship2000 # NTSC

  - Hammerfist # PAL60
  - HardNHeavy # PAL60
  - Harlequin # 10 PAL5
  - Heimdall # -2 PAL5
  - Heimdall2 # 6 PAL5
  - HelterSkelter # 10 PAL5
  - HeroQuest # 4 PAL5
  - HeroQuest2 # 18 PAL5
  - HexumaDe # 0 PAL5
  - Hillsfar # NTSC
  - HiredGuns # 0 PAL5
  - Historyline # 20 PAL5
  - Historyline--Intro # -2 PAL5
  - HollywoodPokerPro # 0 PAL5
  - Hostages # 14 PAL5
  - HudsonHawk # 30 PAL5
  - Hunter # PAL60
  - Hybris # NTSC

  - IK+ # 6 PAL5
  - IkariWarriors  # PAL60
  - Impossamole # 24 PAL5
  - ImpossibleMission2025 # NTSC
  - IndianaJonesAtlantisAct # NTSC
  - IndianaJonesAtlantisAdv # NTSC
  - IndianaJonesTempleOfDoom # PAL60
  - Indianapolis500 # PAL60
  - IndyHeat # 8 PAL5
  - IndyJonesLastCrusAdv # NTSC
  - InnocentUntilCaught # PAL60
  - InsectsInSpace # PAL60
  - International3DTennis # 20 PAL5
  - Interphase # 16 PAL5
  - ItCameFromTheDesert
  - ItCameFromTheDesert # NTSC
  - ItCameFromTheDesert2
  - ItCameFromTheDesert2 # NTSC
  - Ivanhoe # 0 PAL5

  - JaguarXJ220 # 10 PAL5
  - JamesPond # 0 PAL5
  - JamesPond2 # 0 PAL5
  - JamesPond3 # 22 PAL5
  - JimmyWhitesSnooker # PAL60
  - JimPower # 4 PAL5
  - JudgeDredd # 4 PAL5
  - JumpingJackSon # PAL60
  - JungleStrike # PAL60

  - K240 # 0 PAL5
  - Katakis # 0 PAL5
  - KickOff # 4 PAL5
  - KickOff&ExtraTime2Disk # 4 PAL5
  - KickOff2 # 32 PAL5
  - KickOff216 # 32 PAL5
  - KickOff2FinalWhistle # 32 PAL5
  - KickOff2ReturnToEurope # 32 PAL5
  - KidChaos # 20 PAL5
  - KidGloves # NTSC
  - Kikstart2 # PAL60
  - KillingGameShow # -4 PAL5
  - KingOfChicago # NTSC
  - Klax # PAL60
  - KnightsOfTheCrystallion # NTSC
  - Kristal # NTSC
  - Kult # PAL60

  - LamborghiniAmericanChllng # PAL60
  - Larrie # PAL60
  - LaserSquad # NTSC
  - LaserSquadNTSC
  - Leatherneck # NTSC
  - LegendOfFaerghailNTSC # NTSC
  - LegendOfKyrandia # NTSC
  - LeisureSuitLarry3 # NTSC
  - Lemmings # NTSC
  - Lemmings2 # NTSC
  - LightCorridor # PAL60
  - Loom # NTSC
  - LostTreasuresOfInfocom # NTSC
  - LostVikings # NTSC

  - ManiacMansion # NTSC
  - MarbleMadness # NTSC
  - Mercenary # NTSC
  - Mercenary3 # NTSC
  - Midwinter # PAL60
  - Midwinter2 # PAL60
  - Millennium22 # PAL60
  - MindWalker # NTSC
  - MonkeyIsland2 # NTSC
  - Murder # PAL60
  - NaughtyOnes # NTSC
  - Nebulus # PAL60
  - Neuromancer # NTSC
  - NinjaRemix # PAL60
  - NuclearWar # NTSC

  - Obliterator # NTSC
  - Obsession # PAL
  - Odyssey # 28 PAL5 
  - OffShoreWarrior # 8 PAL5
  - OhNoMoreLemmings # NTSC
  - OilImperium # PAL60
  - OneStepBeyond # 13 PAL5
  - OperationCleanstreets # NTSC
  - OperationStealth # PAL60
  - OperationThunderbolt # 24 PAL5
  - OperationWolf # 14 PAL5
  - Oxxonian # PAL

  - PacLand # PAL60
  - Pacmania # PAL60
  - Pandora # PAL60
  - PanzaKickBoxing # PAL60
  - ParaglidingSimulation # PAL60
  - Perihelion # NTSC
  - PGAEuropeanTour # PAL60
  - Phantasie3 # NTSC
  - PioneerPlague # NTSC
  - PipeDream # NTSC
  - Pirates # NTSC
  - Platoon # NTSC
  - Plotting # PAL60
  - Poing  # 0 PAL5
  - Poing2 # 0 PAL5
  - Poing3 # 0 PAL5
  - Poing4 # 0 PAL5
  - Poing5 # 0 PAL5
  - Poing6 # 0 PAL5
  - Poing7 # 0 PAL5
  - Populous # NTSC
  - Populous2&ChallengeGames # NTSC
  - PortsOfCall # NTSC
  - Powermonger # NTSC
  - PrinceOfPersia # NTSC
  - Project1 # PAL60
  - Projectyle # PAL60
  - PurpleSaturnDay # PAL60
  - Puzznic # PAL60

  - Qix # NTSC
  - Quartz # 12 PAL5
  - Questron2 # NTSC
  - Qwak # 20 PAL5

  - Racter # PAL60
  - RailroadTycoon # NTSC
  - RainbowIslands # 10 PAL5
  - RallyCrossChallenge # 25 PAL5
  - Rampart # NTSC
  - RanX # PAL60
  - RBI2Baseball # PAL
  - Realms # PAL60
  - RedHeat # 9 PAL5
  - RedStormRising # NTSC
  - Renegade # PAL60
  - Renegades # PAL
  - Resolution101 # PAL60
  - RevengeOfMutantCamels # NTSC
  - RevengeOfMutantCamels2 # PAL60
  - RickDangerous # 22 PAL5
  - RickDangerous2 # 22 PAL5
  - RickDangerous25 # 22 PAL5
  - RingsOfMedusa # -1 PAL5
  - RiseOfTheDragon # NTSC
  - Roadkill # 24 PAL5
  - RoadwarEuropa # NTSC
  - RobinHoodLegendQuest # PAL60
  - RoboCop # 16 PAL5
  - RoboCop3 # 16 PAL5
  - RocketRanger # NTSC
  - RockNRoll # 12 PAL5
  - RockStarAteMyHamster # 13 PAL5
  - RodLand # 19 PAL5
  - Rogue # PAL60
  - Rotox # PAL60
  - RType # PAL60
  - RType2 # 21 PAL5
  - RuffNTumble # 22 PAL5
  - RygarAGA # 10 PAL5

  - SaintDragon # 30 PAL5
  - Sarcophaser # -3 PAL5 (Music is too fast otherwise)
  - ScoobyDoo&ScrappyDoo # 30 PAL5
  - SecondSamurai # 30 PAL5
  - SecretOfMonkeyIsland # NTSC
  - SensibleGolf
  - SensibleSoccer
  - SensibleSoccer9293
  - SensibleSoccerBulldogBlty
  - SensibleSoccerEuro
  - SensibleTrainSpotting
  - SensibleWorldMoonSoccer
  - SensibleWorldOfSoccer
  - SensibleWorldOfSoccer9596
  - SensibleWorldOfSoccer9697
  - Sentinel # PAL60
  - Settlers # PAL
  - SevenGatesOfJambala # 2 PAL5 (Music is too fast otherwise)
  - ShadowFighter # PAL
  - Shadowlands # 26 PAL5
  - ShadowOfTheBeast # PAL
  - ShadowOfTheBeast2 # PAL
  - ShadowOfTheBeast3 # PAL
  - ShadowWarriors # 2 PAL5
  - Shanghai # NTSC
  - ShaqFu # PAL60
  - ShockWave # PAL60
  - ShufflepuckCafe # NTSC
  - SideWinder # NTSC
  - SideWinder2 # PAL60
  - Silkworm # 16 PAL5
  - SillyPutty # 10 PAL5
  - SimAntHiRes # NTSC
  - SimCity # NTSC
  - SimonTheSorcererAGA # 26 PAL5
  - Simulcra # -6 PAL5
  - Sinbad # NTSC
  - SlamTilt # PAL
  - Sleepwalker # 7 PAL5
  - SlySpySecretAgent # PAL
  - SnowBros # 15 PAL5
  - SoccerKid # 15 PAL5
  - Spaceball # NTSC
  - SpaceCrusade&VoyageBeyond # PAL
  - SpaceHarrier2 # PAL
  - Spaceport # PAL60
  - SpaceTaxi3 # PAL
  - Speedball # NTSC
  - Speedball2 # PAL
  - SperisLegacy # PAL
  - SpindizzyWorlds # PAL60
  - SpittingImage # PAL60
  - Springtime # PAL
  - SpyVsSpy # NTSC
  - SpyVsSpy2TheIslandCaper # NTSC
  - SpyVsSpy3ArcticAntics # NTSC
  - SpyWhoLovedMe # NTSC
  - Starblaze # PAL60
  - Starglider # PAL60
  - Starglider2 # PAL60
  - Statix # PAL
  - StoriaAncestrale
  - StreetRod # NTSC
  - StreetRod2 # NTSC
  - StuntCarRacer # 14 PAL5
  - StuntCarRacerTNT # 14 PAL5
  - SuperCars # 0 PAL5
  - SuperCars2 # 0 PAL5
  - Superfrog # PAL
  - SuperGemZ # PAL
  - SuperHangOn # PAL60
  - SuperHero #26 PAL5
  - SuperMethaneBros # PAL
  - SuperOffRoad # NTSC
  - SuperScrambleSimulator # PAL60
  - SuperSkidmarks # PAL
  - SuperSkidmarks+CD # PAL
  - SuperSkweek # PAL60
  - SuperStardust # PAL
  - SuperTwintris # PAL
  - SuprTennisChmps # PAL
  - Switchblade # 16 PAL5
  - Switchblade2 # 10 PAL5
  - SWIV # PAL
  - SwordOfSodan # PAL60
  - Syndicate # NTSC
  - SyndicateAmericanRevolt # NTSC

  - TeenageQueen # PAL60
  - TempleOfApshaiTrilogy # NTSC
  - Tensai # 20 PAL5
  - Terramex # PAL60
  - TestDrive2 # NTSC
  - TetrisMirrorsoft # NTSC
  - TetrisPro # PAL
  - TheirFinestHour # NTSC
  - ThemePark # NTSC
  - ThreeStooges # NTSC
  - Thunderbirds # PAL60
  - ThunderHawkAH73M # -2 PAL5
  - TinyTroops # PAL
  - TitusTheFox # PAL60
  - Toki # 14 PAL5
  - TomAndTheGhost # PAL60
  - Tony&Friends # 2 PAL5
  - Toobin # 5 PAL5
  - TorvakTheWarrior # PAL60
  - TotalEclipse # NTSC
  - TotalRecall #PAL60
  - TowerOfBabel # PAL60
  - TrapsNTreasures # PAL
  - TreasureIslandDizzy # PAL60
  - TreasureTrap # PAL60
  - TrexWarrior # PAL
  - TurboRaketti2Fi # PAL
  - Turrican # 4 PAL5
  - Turrican2 # 4 PAL5
  - Tusker # 30 PAL5
  - TVSportsBasketball # NTSC
  - TVSportsFootball # NTSC
  - Twintris # PAL 
  - TwinWorld # 10 PAL5
  - TyphoonThompson # NTSC

  - UFOEnemyUnknown # 30 PAL5 (British developer, music sounds correct in PAL)
  - Ugh # PAL
  - Ultima5 # NTSC
  - Universe 
  - Unreal # 24 (NTSC)
  - Untouchables # 20 PAL5
  - Uridium2 # PAL60 (Shoot'em up)

  - Vaxine # 4 PAL5
  - VenusTheFlytrap 
  - VirocopAGA # 21 PAL5
  - Virus
  - Voyager # 22 PAL5
  - Vroom # -2 PAL5
  - Vyrus # PAL60 (European developer, but shoot'em-up)

  - Walker # -3 PAL5
  - WalkerDecrunched # Is Decrunched canonical? More samples? (applied PAL5 to all)
  - Warhead # -2 PAL5
  - WarInMiddleEarth # NTSC
  - WarzoneCoreDesign # 6 PAL5
  - Waxworks # 26 PAL5
  - WCLeaderBoard # NTSC
  - WeirdDreams # NTSC
  - WesternGames # 5 PAL5
  - WIEuropeIsCarmenSandiego # NTSC
  - Wings # NTSC
  - WingsOfDeath # PAL60
  - WingsOfFury # NTSC
  - WITUSAIsCarmenSandiego # NTSC
  - WITWIsCarmenSandiego # NTSC
  - Wizball # 14 PAL5
  - Wizkid # Actual PAL (although with large margins?)
  - WizNLiz # Actual PAL
  - Wolfchild # 2 PAL5
  - WorldGames # NTSC
  - Worms2MB # -32 (PAL)
  - WormsDCAGA12MB # -10 (PAL)

  - Xenon # NTSC
  - Xenon2 # 16 PAL5 (sadly, music is too fast in NTSC)
  - XOut # PAL60
  - XOut2Disk # PAL60
  - Xybots # PAL60

  - YoJoe # PAL60 (makes the artwork look correct, also Hudson Soft)
  - Yolanda # -2 PAL5

  - ZakMcKracken # NTSC
  - ZanyGolf # NTSC
  - Zarathrusta # 1 PAL5
  - Zeewolf # PAL60
  - Zeewolf2 # # PAL60
  - Zool # PAL
  - ZOut # 12 PAL5 (but seems to only stretch in the vertical direction?)
