--- # AGS2 Menu structure
- Current:
  - Turrican2AGA
  - Cadaver&ThePayoff
  - Cadaver&ThePayoff--TPO
  - CastleMaster&TheCrypt
  - CastleMaster&TheCrypt--CM2
- C1:
  - Cadaver
  - CastleMaster
- C2:
  - Cadaver&ThePayoff
- C3:
  - Cadaver&ThePayoff--TPO
- Test:
  - note: Test for builder options
  - Andromeda-Rule30: { scale: 6, v_offset: 48 }
  - BaygonAGA: Melon!
  - BrunosMusicBox3: { v_offset: 4 }
  - Coma: { note: COMA! }
  - Nested:
    - How2SkinACat
    - Delphine-Collection: { unavailable: True }
    - HumanTarget
    - Interference
