--- # AGS2 Menu structure
- Test:
  - demo--microconcept--microconcept # both "note" and "issues"
  - demo--coppermaster--coppermaster # 5x cropped demo
  - demo-notwhdl--melon-fisherhawkdr # test 6x!
