--- # AGS2 Menu structure
- Test:
  - Elvira
  - Elvira2
  - LostPatrol
  - MindWalker
  - Nitro
  - Turrican
  - Turrican2
  - Turrican3
  - PushOver
  - OneStepBeyond
  - Spaceballs-Peek
  - Lotus
  - Lotus2
  - Lotus3
  - SuperCars
  - SuperCars2
  - Alcatraz
  - Hostages
  - BombJack
  - MightyBombJack
  - ShadowOfTheBeast
  - ShadowOfTheBeast2
  - ShadowOfTheBeast3
  - Lemmings
  - Lemmings2
  - AllNewWorldOfLemmings
  - OhNoMoreLemmings
  - NorthAndSouth
  - Bobo
  - Speedball
  - Speedball2
  - JamesPond
  - JamesPond2
  - RickDangerous
  - RickDangerous2
  - Lionheart
  - MrNutz
  - MidnightResistance
  - RedHeat
  - RoboCop
  - RoboCop3
  - Untouchables
  - Cabal
  - LiquidKids
  - Ivanhoe
  - Toki
  - K240
  - Blasteroids
  - EscapeFTPOTRobotMonsters
  - ShadowWarriors
  - SpaceHarrier2
  - Toobin
  - Maya
  - curseofenchantia
  - Frenetic
  - Impossamole
  - game--thunderhawkah73m--thunderhawkah73m
  - game--torvakthewarrior--torvakthewarrior
  - game--warzonecoredesign--warzonecoredesign
  - game--wolfchild--wolfchild
  - game--blastar--blastar
  - game--actionfighter--actionfighter
  - game--axelsmagichammer--axelsmagichammer
  - game--narcopolice--narcopolice
  - game--saintdragon--saintdragon
  - game--judgedredd--judgedredd
  - game--ninjawarriors--ninjawarriors
  - TFX
  - Superhero
  - Tensai
  - PioneerPlague
  - Springtime
  - LandGenesis
  - SpaceTaxi3
  - FireAndIce
  - Eco

- Best-of Lists:
  - note: Top games lists compiled or voted by magazines back in the day as well as contemporary outlets.
  - Amiga Lore Top 100:
    - ranked_list: True
    - note: Amiga Lore's aggregate review score ranking,
            taking into account the largest publications of
            the era from across the continent. A Metacritic
            equivalent for the platform, if you will.
            Some duplicate entries exist, since rereleases
            and CD32 versions are considered separately.
    - Populous2&ChallengeGames
    - SensibleWorldOfSoccer9596
    - CannonFodder
    - Lemmings
    - MonkeyIsland2
    - SensibleWorldOfSoccer
    - Flashback
    - Speedball2
    - DesertStrike
    - FireAndIce
    - FirstSamurai
    - FormulaOneGrandPrix4Disk
    - Hunter
    - JimmyWhitesSnooker
    - Lemmings2
    - Populous
    - ProjectXSE
    - ThemePark
    - Turrican2
    - ShadowFighter
    - MegaLoMania
    - KickOff2
    - CannonFodderCD32
    - BeneathAStlSky
    - Delphine-Collection: not_available
    - DungeonMaster
    - Frontier
    - PinballIllusions
    - Zool
    - SensibleSoccer9293
    - Settlers
    - Speedball2
    - StuntCarRacer
    - SWIV
    - Syndicate
    - IndianaJonesAtlantisAdv
    - Gods
    - Greatest-Collection: not_available
    - EyeOfTheBeholder
    - ChaosEngine
    - CruiseForACorpse
    - PuttySquad
    - JamesPond2
    - Lotus
    - PinballIllusions
    - RainbowIslands
    - RoboCop3
    - SecretOfMonkeyIsland
    - AlienBreed2
    - Award-Winners-Gold: not_available
    - Banshee
    - BodyBlows
    - Dune2
    - FireAndIce
    - JungleStrike
    - Leander
    - FourCrystalsOfTrazere
    - Lionheart
    - Lotus2
    - Nebulus
    - NoSecondPrize
    - PinballFntsies
    - ProjectX
    - Putty
    - ThunderHawkAH73M
    - SensibleSoccerEuro
    - SimCity
    - Starglider2
    - SuperStardust
    - SuprTennisChmps
    - Superfrog
    - OhNoMoreLemmings
    - Goal
    - Gunship2000
    - EyeOfTheBeholder2
    - Civilization
    - AlienBreedSpecialEdition
    - ArcherMacLeansPool
    - Banshee
    - BCKid
    - Deuteros
    - F15StrikeEagle2
    - F19StealthFighter
    - F29Retaliator
    - Falcon
    - Frontier
    - Harlequin
    - LegendOfKyrandia
    - LostVikings
    - PGAEuropeanTour
    - PGATourGolf
    - PinballPrelude
    - Populous
    - ProTennisTour2
    - RailroadTycoon
    - TitusTheFox
    - TowerOfBabel
    - Turrican
    - Xenon2
    - LostTreasuresOfInfocom
  - Amiga Power Top 100 (1991):
    - ranked_list: True
    - note: The Top 100 games for the Commodore Amiga according to UK games magazine Amiga Power in 1991.
    - RainbowIslands
    - Lemmings
    - Speedball2
    - SimCity
    - Virus
    - Populous
    - KickOff2
    - Falcon
    - Indianapolis500
    - StuntCarRacer
    - Pang
    - PrinceOfPersia
    - SpindizzyWorlds
    - Nebulus
    - CarrierCommand
    - DungeonMaster
    - RickDangerous2
    - Ultima5
    - NewZealandStory
    - Sentinel
    - Damocles
    - Paradroid90
    - Plotting
    - TyphoonThompson
    - LaserSquad
    - Klax
    - SWIV
    - IndyJonesLastCrusAdv
    - F19StealthFighter
    - EMotion
    - Captive
    - Powermonger
    - Xenon2
    - Puzznic
    - SuperOffRoad
    - F29Retaliator
    - Vaxine
    - Interphase
    - CastleMaster
    - CarVup
    - SuperHangOn
    - ProTennisTour2
    - Starglider2
    - Shanghai
    - Lotus
    - OperationStealth
    - WCLeaderBoard
    - ArkanoidRevengeOfDoh
    - BattleSquadron
    - TowerOfBabel
    - Wings
    - Cadaver
    - BubbleBobble
    - LeisureSuitLarry3
    - Archipelagos
    - HelterSkelter
    - Bombuzal
    - BattleCommand
    - KillingGameShow
    - IK+
    - Warhead
    - FA18Interceptor
    - FutureWars
    - NightShift
    - Silkworm
    - Midwinter
    - Pacmania
    - KidGloves
    - Projectyle
    - BalanceOfPower1990Ed
    - RickDangerous
    - Loom
    - RocketRanger
    - SaintDragon
    - Elite
    - Quartz
    - Flood
    - BuggyBoy
    - ZanyGolf
    - PipeDream
    - TotalEclipse
    - DragonBreed
    - JamesPond
    - VenusTheFlytrap
    - TetrisMirrorsoft
    - TVSportsFootball
    - DistantArmies
    - Turrican
    - TreasureTrap
    - BatmanTheMovie
    - Switchblade
    - SuperCars
    - TheirFinestHour
    - MiG29Fulcrum
    - MontyPythonsFlyCir
    - GoldenAxe
    - GhoulsNGhosts
    - RedStormRising
    - Xybots
    - GrandMonsterSlam

- Themed Lists:
  - note: Lists compiled with a specialized theme or focus.
  - Amiga Exclusives:
    - note: A selection of games exclusive to the Amiga platform.
    - Agony
    - Akira
    - AllTerrainRacing
    - Ambermoon
    - Amegas
    - Amnios
    - Apidya
    - Aquaventura
    - ArabianNights
    - AssassinSpecialEdition
    - Banshee
    - BaseJumpers
    - Benefactor
    - BillsTomatoGame
    - BlackCrypt
    - Blob
    - BrianTheLion
    - CardiaxxTeam17
    - ChaosEngine2
    - CrazySueGoesOn
    - Cyberpunks
    - Cytron
    - Darkmere
    - Datastorm
    - DisposableHero
    - DojoDan
    - Ebonstar
    - Elfmania
    - FA18Interceptor
    - FinalCountdown
    - Fuzzball
    - Globdule
    - HeroQuest2
    - Hybris
    - ImpossibleMission2025
    - ItCameFromTheDesert2
    - K240
    - KidChaos
    - KnightsOfTheCrystallion
    - Lionheart
    - MindWalker
    - MrNutz
    - NathanNever
    - NaughtyOnes
    - NeverMind
    - Oath
    - OperationCleanstreets
    - ParaglidingSimulation
    - Perihelion
    - PioneerPlague
    - Premiere
    - Roadkill
    - RuffNTumble
    - ShadowOfTheBeast3
    - Skidmarks
    - SperisLegacy
    - SphericalWorlds
    - SpringTime
    - Superfrog
    - TinyTroops
    - TrapsNTreasures
    - Uridium2
    - Virocop
    - Walker
    - Wings
    - WormsDC
    - Zarathrusta
    - Zeewolf
  - Cyberpunk:
    - note: A selection of cyberpunk themed games.
    - BeneathAStlSky
    - BloodNet
    - DGeneration
    - DreamWeb
    - Extase
    - HiredGuns
    - Interphase
    - Neuromancer
    - RiseOfTheDragon
    - Syndicate
  - Deep Cuts:
    - note: Dare we say hidden gems?
    - AlphaWaves
    - BladeWarrior
    - DGeneration
    - GalacticTheXmasEdition
    - LaserSquad
    - MegaLoMania
    - MindWalker
    - Psyborg
    - TyphoonThompson
  - Esoteric:
    - note: A look in the obscure, sometimes incomprehensible, corners of the Amiga library.
    - 3001OConnorsFight
    - AlienDrugLords
    - Archipelagos
    - Colony
    - KnightsOfTheCrystallion
    - Kristal
    - Mercenary3
    - MindWalker
    - PioneerPlague
    - PurpleSaturnDay
    - Racter
    - Sentinel
    - Sinbad
    - TowerOfBabel
    - WeirdDreams
  - French Touch:
    - note: The French Amiga studios developed a dinstict style, heavily influenced by domestic comics and easy access to manga and anime.
    - AnotherWorld
    - AnotherWorldLostLevel
    - BeachVolley
    - BestOfTheBest
    - BioChallenge
    - Hostages
    - FutureWars
    - Ivanhoe
    - Kult
    - LiquidKids
    - Lorna
    - MetalMutant
    - NorthAndSouth
    - OperationStealth
    - RanX
  - Good Arcade Conversions:
    - note: Steer clear of US Gold and there's some decent to good arcade conversions in the Amiga library.
    - Arkanoid
    - BubbleBobble
    - BuggyBoy
    - EmpireStrikesBack
    - NewZealandStory
    - NinjaWarriors
    - Pang
    - ParasolStars
    - RainbowIslands
    - RodLand
    - RType
    - RygarAGA
    - Silkworm
    - SnowBros
    - TinyBobble
  - Licensed Games:
    - note: Surprisingly playable or interesting games based on licensed IP.
    - AddamsFamily
    - BatmanCapedCrusader
    - BatmanTheMovie
    - HudsonHawk
    - RoboCop3
    - ScoobyDoo&ScrappyDoo
    - TotalRecall
  - Vector Graphics:
    - note: A sampling of games with wireframe and polygonal graphics.
    - 3DGalax
    - ATF2
    - AlphaWaves
    - AirSupport
    - Alianator
    - Archipelagos
    - CarrierCommand
    - CastleMaster
    - Cybercon3
    - Damocles
    - Epic
    - Hunter
    - Interphase
    - LightCorridor
    - Mercenary
    - Mercenary3
    - Midwinter
    - NoSecondPrize
    - Resolution101
    - RoboCop3
    - Sentinel
    - Starglider
    - Starglider2
    - Starblaze
    - StuntCarRacer
    - EmpireStrikesBack
    - TotalEclipse
    - TowerOfBabel
    - TrexWarrior
    - Virus
    - Voyager
  - Technically Impressive:
    - note: Not necessarily good games (mostly the opposite!), but containing some, for the time, advanced technical trickery.
    - BrianTheLion
    - DrivinForce
    - Elfmania
    - JimPower
    - Lionheart
    - MrNutz
    - ShadowOfTheBeast
    - ShockWave
    - SwordOfSodan
    - Unreal

- Gameographies:
  - note: Notable developer gameographies.\n\n(Restricted to WHDL adapted games, so not necessarily complete lists.)
  - "< By Composer >":
    - note: Games with music by notable composers.\n\n(Not necessarily complete lists.)
    - Chris Hülsbeck:
      - note: Arguably the most loved Amiga composer of all time, and also creator of the very interesting TFMX music software.
      - AdventuresOfQuik&Silva
      - Apidya
      - Apprentice
      - BadCat
      - BattleIsle
      - BCKid
      - BundesligaMngrHatt
      - CaribbeanDisasterDe
      - CarlLewisChallenge
      - CircusAttractions
      - DangerFreak
      - GemX
      - GrandMonsterSlam
      - HardNHeavy
      - HexumaDe
      - HollywoodPokerPro
      - JimPower
      - Logistic
      - Masterblazer
      - MetalLaw
      - MUDS
      - Oxxonian
      - RockNRoll
      - RType
      - SecretOfMonkeyIsland
      - Spaceball
      - Turrican
      - Turrican2
      - Turrican3
      - XOut
      - ZOut
    - Karsten Obarski:
      - note: Maker of the original Sound Tracker software, and a prolific composer in the very early days of Amiga.
      - Amegas
      - BrandsHatch
      - CrystalHammerV2
      - Dyter07
      - FateGatesOfDawn
      - FutureTank
      - Larrie
      - OilImperium
      - Project1
      - Sarcophaser
      - WindowWizard
    - Follin Brothers:
      - note: The Amiga was the legendary brothers Tim & Geoff least favorite platform, and you can sort of tell...
      - BionicCommando
      - Gauntlet3
      - GhoulsNGhosts
      - LEDStorm
      - Puzznic
      - Qix
      - Renegade
      - SlySpySecretAgent
  - Assembly Line, The:
    - note: While most known for helping out the Bitmap Bros on Xenon 2, the awesome and quirky puzzle games represent their finest work.
    - Cybercon3
    - EMotion
    - Exterminator
    - Interphase
    - PipeDream
    - Vaxine
    - Xenon2
  - Bitmap Brothers:
    - note: The original "style over substance" game studio. Their catalogue is worth checking out for Dan Malone and Mark Coleman's exquisite pixeling style alone.
    - Cadaver
    - CadaverThePayoff
    - ChaosEngine
    - ChaosEngine2
    - Gods
    - MagicPockets
    - Speedball
    - Speedball2
    - Xenon
    - Xenon2
  - Blue Byte:
    - note: Purveyors of fine strategy games (and tennis!).
    - Atomino
    - BattleIsle&DataDisks
    - BattleIsle&DataDisks--Intro
    - BattleIsle&DataDisks--ALSS
    - BattleIsle&DataDisks--Moon
    - ProTennisTour
    - ProTennisTour2
    - Historyline
    - Historyline--Intro
    - Historyline--Outro
    - Settlers
    - TomAndTheGhost
    - TwinWorld
  - Brøderbund:
    - DownhillChallenge
    - PrinceOfPersia
    - ShufflepuckCafe
    - TyphoonThompson
    - WIEuropeIsCarmenSandiego
    - WITUSAIsCarmenSandiego
    - WITWIsCarmenSandiego
    - WingsOfFury
  - Delphine Software:
    - AnotherWorld
    - AnotherWorldLostLevel
    - BioChallenge
    - CastleWarrior
    - CruiseForACorpse
    - Flashback
    - FutureWars
    - OperationStealth
    - ShaqFu
  - Digital Illusions:
    - Amiganoid
    - Benefactor
    - PinballDreams
    - PinballFntsies
    - PinballIllusions
  - DMA Design:
    - AllNewWorldOfLemmings
    - BloodMoney
    - HiredGuns
    - Lemmings
    - Lemmings2
    - Menace
    - OhNoMoreLemmings
    - Walker
  - Factor 5:
    - BCKid
    - Denaris
    - Katakis
    - RType
    - Tony&Friends
    - Turrican
    - Turrican2
    - Turrican3
  - Graftgold:
    - EmpireSoccer94
    - FireAndIce
    - Paradroid90
    - RainbowIslands
    - Realms
    - Simulcra
    - SuperOffRoad
    - Uridium2
    - Virocop
  - Horror Soft:
    - Elvira
    - Elvira2
    - PersonalNightmare
    - Waxworks
  - Llamasoft:
    - Defender2
    - Llamatron
    - RevengeOfMutantCamels
    - RevengeOfMutantCamels2
    - SuperGridRunner
  - Magnetic Fields:
    - CrystalDragon
    - KidChaos
    - Kikstart2
    - Lotus
    - Lotus2
    - Lotus3
    - MFTanks
    - Pod
    - SuperCars
    - SuperCars2
    - SuperScrambleSimulator
  - Random Access, Storm:
    - note: Purveyors of fine arcade conversions.
    - BigRun
    - FinalBlow
    - IndyHeat
    - JudgeDredd
    - Narc
    - NinjaWarriors
    - RodLand
    - SaintDragon
    - Silkworm
    - SWIV
  - Reflections:
    - Awesome
    - Ballistix
    - BrianTheLion
    - ShadowOfTheBeast
    - ShadowOfTheBeast2
    - ShadowOfTheBeast3
  - reLINE:
    - Amegas
    - CrystalHammerV2
    - Dyter07
    - OilImperium
    - Spaceport
    - WesternGames
    - WindowWizard
  - Sensible Software:
    - CannonFodder
    - CannonFodder2
    - CannonFodder2AlienLevels
    - CannonFodderNewCampaign
    - CannonFodderPlus
    - InsectsInSpace
    - International3DTennis
    - MegaLoMania
    - SensibleGolf
    - SensibleSoccer
    - SensibleSoccerBulldogBlty
    - SensibleWorldMoonSoccer
    - SensibleWorldOfSoccer
    - SensibleWorldOfSoccer9697
    - SensibleTrainSpotting
    - Wizball
    - Wizkid
  - Travellers Tales:
    - Leander
    - Puggsy
  - Vectordean:
    - AquaticGames
    - BadCompany
    - DogsOfWar
    - FireAndBrimstone
    - JamesPond
    - JamesPond2
    - JamesPond3
    - Yolanda
  - Westwood:
    - Battletech
    - CaliforniaGames
    - DragonStrike
    - Dune2
    - EyeOfTheBeholder
    - EyeOfTheBeholder2
    - GoofysRailwayExpress
    - Hillsfar
    - LegendOfKyrandia
    - Phantasie3
    - Questron2
    - RoadwarEuropa
    - TempleOfApshaiTrilogy
    - WorldGames

- Best of Multiplayer:
  - note: Our top picks for multiplayer action.
  - BattleIsle
  - ChaosEngine
  - DogsOfWar
  - DynaBlaster
  - HiredGuns
  - Historyline
  - JaguarXJ220
  - Lotus
  - Moonstone
  - Nitro
  - OilImperium
  - Pang
  - PortsOfCall
  - Rampart
  - RodLand
  - SensibleGolf
  - SensibleWorldOfSoccer9596
  - Settlers
  - Silkworm
  - SlamTilt
  - Speedball2
  - SuperCars2
  - SuperSkidmarks+CD
  - SWIV
  - Twintris
  - Worms

- Top Picks by Genre:
  - note: Our personal top picks, sorted by genre.
  - Action, Misc:
    - DynaBlaster
    - Hostages
    - Paradroid90
    - Psyborg
    - Walker
  - Adventure, Action:
    - BladeWarrior
    - Cadaver
    - Darkmere
    - DGeneration
    - HiredGuns
    - ItCameFromTheDesert
    - KingOfChicago
    - Moonstone
    - RocketRanger
    - Wings
  - Adventure, RPG:
    - Ambermoon
    - BlackCrypt
    - Captive
    - DungeonMaster
    - EyeOfTheBeholderAGA
    - EyeOfTheBeholder2AGA
    - FourCrystalsOfTrazere
    - HeroQuest
    - Rogue
    - Shadowlands
  - Adventure, Misc:
    - DejaVu
    - DejaVu2LostInLasVegas
    - Elvira
    - Elvira2
    - Murder
  - Adventure, Point & Click:
    - AlteredDestiny
    - BeneathAStlSky
    - DarkSeed
    - FlightOfTheAmazonQueen
    - IndianaJonesAtlantisAdv
    - IndyJonesLastCrusAdv
    - InnocentUntilCaught
    - Loom
    - ManiacMansion
    - MonkeyIsland2
    - RiseOfTheDragon
    - SecretOfMonkeyIsland
    - Universe
  - Martial Arts:
    - note: While Street Fighter style fighting games were a poor fit for Amiga, here's some notable old school martial arts games.
    - BestOfTheBest
    - Budokan
    - IK+
  - Pinball:
    - note: A popular enough genre on the Amiga to deserve its own list.
    - Obsession
    - PinballDreams
    - PinballFntsies
    - PinballIllusions
    - SlamTilt
  - Platform:
    - ArabianNights
    - AddamsFamily
    - BCKid
    - Flood
    - JamesPond2
    - KidChaos
    - RickDangerous
    - SoccerKid
    - TrapsNTreasures
  - Platform, Action:
    - note: Run'n'gun and platform shooters.
    - Leander
    - RuffNTumble
    - SecondSamurai
    - Switchblade
    - Switchblade2
    - Turrican2
    - YoJoe
  - Platform, Arcade:
    - note: Arcade style, mostly single screen, platformers.
    - BaseJumpers
    - BombJack
    - BubbleBobble
    - Fuzzball
    - NaughtyOnes
    - Pang
    - RodLand
    - SnowBros
    - WizNLiz
  - Platform, Cinematic:
    - AnotherWorld
    - Flashback
    - PrinceOfPersia
  - Platform, Puzzle:
    - Benefactor
    - BubbaNStix
    - Builderland
    - Globdule
    - ShadowOfTheBeast3
    - SillyPutty
    - Ugh
  - Puzzle:
    - ClikClak
    - Deflektor
    - DeviousDesigns
    - EMotion
    - Lemmings
    - Logical
    - OneStepBeyond
    - PipeDream
    - PushOver
    - SpringTime
    - Statix
    - SuperSkweek
    - SuperTwintris
    - TetrisPro
    - Twintris
  - Racing, Into Screen:
    - JaguarXJ220
    - LamborghiniAmericanChllng
    - Lotus
    - Lotus2
    - BuggyBoy
    - StuntCarRacer
    - TestDrive2
    - Vroom
  - Racing, Top Down:
    - AllTerrainRacing
    - BadLands
    - Carnage
    - IndyHeat
    - Nitro
    - Skidmarks
    - SuperCars2
    - SuperSkidmarks+CD
  - Shoot'em Up:
    - Apidya
    - BattleSquadron
    - Datastorm
    - DisposableHero
    - GalacticTheXmasEdition
    - Hybris
    - MegaTyphoon
    - Pod
    - Silkworm
    - Uridium2
  - Simulation:
    - Floor13
    - OilImperium
    - PortsOfCall
    - RailroadTycoon
    - SimCity
  - Sports:
    - ArcadePool
    - CaliforniaGames
    - ProTennisTour
    - RBI2Baseball
    - SensibleGolf
    - SensibleWorldOfSoccer9697
  - Sports, Fantasy:
    - AquaticGames
    - Botics
    - GrandMonsterSlam
    - Projectyle
    - ShufflepuckCafe
    - Speedball2
  - Strategy:
    - BattleIsle
    - CelticLegends
    - Centurion
    - Dune2
    - HistoryLine
    - LaserSquad
    - MegaLoMania
    - NuclearWar
    - Populous
    - Settlers
  - Strategy, Action:
    - CannonFodder
    - DefenderOfTheCrown
    - LemmingsImage
    - LostPatrol
    - NorthAndSouth
    - Pirates
    - Rampart
