--- # AGS2 Menu structure
- Test:
  - SnowBros
  - SoccerKid
  - Worthy
#- Gamepad Support:
#  - note: Games supporting two or more buttons.
#  - BumpNBurnCD32
#  - DeathMaskAGA
#  - MeanArenas
#  - FantasticDizzy
