--- # AGS2 Menu structure
- Test:
  - game--arabiannights--arabiannights
  - game--awesome--awesome
  - game--batmanthemovie2disk--batmanthemovie2disk
  - game--blastar--blastar
  - game--bonecruncher--bonecruncher
  - game--bonecruncherenhanced--bonecruncherenhanced
  - game--crystaldragon--crystaldragon # still doesn't launch
  - game--dangerfreak--dangerfreak # Lots of gfx corruption
  - game--fireandicecd32--fireandicecd32  
  - game--fire&icexmasdemo--fire&icexmasdemo
  - game--flashback--flashback
  - game--international3dtennis--international3dtennis
  - game--internationaltennis--internationaltennis
  - game--jimpower--jimpower
  - game--katakis2disk--katakis2disk # Never gets past asking for data disk
  - game--kidchaos--kidchaos
  - game--landgenesisagacd--landgenesisagacd
  - game--supercars2--supercars2
  - game--unrealntsc--unrealntsc
  - game--yolandaimage--yolandaimage
