--- # AGS2 Menu structure
- About:
  - note: 'MEGA AGS 2022.10.01'
  - Nothing to see here:
    - note: Intentionally left blank.

- Current:
  - image: [{"op":"tx", "txt":"ASS"}, {"op":"tx", "txt":"P*SS", "size":100, "color":"#f0f"}]
  - AbyssDone
  - BadDudesVsDragonNinja
  - FFPUnicodeAttac
  - MrsBeanbag-BeSheep
  - ParadoxFutureBike
  - Grapevine01
  - Grapevine02
  - Grapevine03
  - Grapevine04
  - WorldCharts01
  - WorldCharts02
  - WorldCharts03
  - WorldCharts04
  - WorldCharts05
  - WorldCharts07
  - WorldCharts09
  - WorldCharts10
  - WorldCharts11
  - WorldCharts12
  - WorldCharts13
  - WorldCharts15
  - StolenData01
  - StolenData02
  - StolenData03
  - StolenData04
  - StolenData05

- Ordering Test:
  - Order RANKED:
    - rank: 2
    - ordering: "ranked"
    - note: From /v/'s Recommended Games Wiki
            (vsrecommendedgames.fandom.com/wiki/Amiga)
    - Agony
    - ShadowOfTheBeast
  - Order ORDERED:
    - rank: 3
    - ordering: "ordered"
    - note: 45 Games That Defined the AMIGA 500, according to It's a P/XEL thing.\n\n(Chronologically ordered.)
    - IK+
    - BatmanTheMovie
    - StuntCarRacer: { rank: 0 }
    - ItCameFromTheDesert
    - Populous
  - Order RELEASE:
    - rank: 1
    - ordering: "release"
    - note: By release date
    - EyeOfTheBeholder2
    - Lemmings
    - Speedball2
    - Turrican2
    - Worms

- Test:
  - note: Test for builder options
  - Andromeda-Rule30: { scale: 6, v_offset: 48 }
  - BaygonAGA: Melon!
  - BrunosMusicBox3: { v_offset: 4, image: { op: "tx", txt: "BRUNO", size: 90 } }
  - Coma: { note: COMA! }
  - Nested:
    - How2SkinACat
    - Delphine-Collection: { unavailable: True }
    - HumanTarget
    - Interference
