--- # AGS2 Menu structure
- Test:
  - game--3001oconnorsfight--3001oconnorsfight
  - game--3dgalax--3dgalax
  - game--actionfighter--actionfighter
  - game--addamsfamily--addamsfamily
  - game--adventuresofquik&silva--adventuresofquik&silva
  - game--agonyntsc--agonyntsc
  - game--akira--akira
  - game--akiracd32--akiracd32
  - game--alcatraz--alcatraz
  - game--alianator--alianator
  - game--alphawaves--alphawaves
  - game--ambermoon--ambermoon
  - game--ambermoonde--ambermoonde
  - game--amnios--amnios
  - game--anotherworld--anotherworld
  - game--anotherworldlostlevel--anotherworldlostlevel
  - game--apprentice--apprentice
  - game--arabiannights--arabiannights
  - game--arkanoidrevengeofdoh--arkanoidrevengeofdoh
  - game--astaroth--astaroth
  - game--atf2--atf2
  - game--awesome--awesome
  - game--axelsmagichammer--axelsmagichammer
  - game--badcat--badcat
  - game--badlands--badlands
  - game--ballistix--ballistix
  - game--batmancapedcrusader--batmancapedcrusader
  - game--batmanthemovie2disk--batmanthemovie2disk
  - game--battlecommand--battlecommand
  - game--bckid--bckid
  - game--beachvolley--beachvolley
  - game--beneathastlsky--beneathastlsky
  - game--beneathastlskycd32--beneathastlskycd32
  - game--beneathastlskycd32novoice--beneathastlskycd32novoice
  - game--beneathastlskyde--beneathastlskyde
  - game--beneathastlskyfr--beneathastlskyfr
  - game--beneathastlskyit--beneathastlskyit
  - game--beneathastlskyse--beneathastlskyse
  - game--benefactor--benefactor
  - game--benefactorcd32--benefactorcd32
  - game--bigrun--bigrun
  - game--billstomatogamentsc--billstomatogamentsc
  - game--biochallenge--biochallenge
  - game--bioniccommando--bioniccommando
  - game--biplaneduel--biplaneduel
  - game--bladewarrior--bladewarrior
  - game--blastar--blastar
  - game--blasteroids--blasteroids
  - game--blob--blob
  - game--bloodmoney--bloodmoney
  - game--bloodnetaga--bloodnetaga
  - game--bobo--bobo
  - game--bobofr--bobofr
  - game--bombjack--bombjack
  - game--bombuzal--bombuzal
  - game--bonecruncher--bonecruncher
  - game--bonecruncherenhanced--bonecruncherenhanced
  - game--botics--botics
  - game--brandshatch--brandshatch
  - game--brianthelionaga--brianthelionaga
  - game--bubbanstix--bubbanstix
  - game--builderland--builderland
  - game--bundesligamngrhattagade--bundesligamngrhattagade
  - game--cabal--cabal
  - game--cadaver--cadaver
  - game--cadaver&thepayoff--cadaver&thepayoff
  - game--cadaverdemos--cadaverdemos
  - game--cadaverthepayoff--cadaverthepayoff
  - game--cannonfodder--cannonfodder
  - game--cannonfodder2--cannonfodder2
  - game--cannonfodder2alienlevels--cannonfodder2alienlevels
  - game--cannonfoddercd32--cannonfoddercd32
  - game--cannonfoddernewcampaign--cannonfoddernewcampaign
  - game--cannonfodderplus--cannonfodderplus
  - game--cannonsoccer--cannonsoccer
  - game--carllewischallenge--carllewischallenge
  - game--carvup--carvup
  - game--castlemaster--castlemaster
  - game--castlemaster2--castlemaster2
  - game--castlewarrior--castlewarrior
  - game--chambersofshaolin--chambersofshaolin
  - game--chaosengine--chaosengine
  - game--chaosenginecd32--chaosenginecd32
  - game--chuckrock--chuckrock
  - game--chuckrock2--chuckrock2
  - game--circusattractions--circusattractions
  - game--crazysue--crazysue
  - game--crazysuegoeson--crazysuegoeson
  - game--cruiseforacorpse--cruiseforacorpse
  - game--crystaldragon--crystaldragon
  - game--crystalhammerv2--crystalhammerv2
  - game--curseofenchantiafast--curseofenchantiafast
  - game--cybercon3--cybercon3
  - game--dangerfreak--dangerfreak
  - game--darkmere--darkmere
  - game--darkseed--darkseed
  - game--darkseedcd32--darkseedcd32
  - game--datastorm--datastorm
  - game--defender2--defender2
  - game--denaris1disk--denaris1disk
  - game--deuteros--deuteros
  - game--disposablehero--disposablehero
  - game--dogsofwar--dogsofwar
  - game--dojodan--dojodan
  - game--doodlebug--doodlebug
  - game--dragonbreed--dragonbreed
  - game--dreamwebaga--dreamwebaga
  - game--drivinforce--drivinforce
  - game--dune--dune
  - game--dyter07--dyter07
  - game--elvira--elvira
  - game--elvira2--elvira2
  - game--emeraldmine--emeraldmine
  - game--emeraldmine2--emeraldmine2
  - game--emeraldmine3--emeraldmine3
  - game--emeraldminescd--emeraldminecd
  - game--emotion--emotion
  - game--empiresoccer94--empiresoccer94
  - game--epic&missiondisk--epic&missiondisk
  - game--epic&missiondisk--epic&missiondisk--xm
  - game--escapeftpotrobotmonsters--escapeftpotrobotmonsters
  - game--extase--extase
  - game--exterminator--exterminator
  - game--f19stealthfighterntsc--f19stealthfighterntsc
  - game--f29retaliator--f29retaliator
  - game--fantasticdizzyaga--fantasticdizzyaga
  - game--fantasyworlddizzy--fantasyworlddizzy
  - game--fascination--fascination
  - game--fategatesofdawnuncensored--fategatesofdawnuncensored
  - game--finalblow--finalblow
  - game--finalcountdown--finalcountdown
  - game--fire&icexmasdemo--fire&icexmasdemo
  - game--fireandbrimstone--fireandbrimstone
  - game--fireandicecd32--fireandicecd32
  - game--firstsamurai--firstsamurai
  - game--flashback--flashback
  - game--frenetic--frenetic
  - game--futurewars--futurewars
  - game--globdule--globdule
  - game--goal--goal
  - game--gods--gods
  - game--goofysrailwayexpress--goofysrailwayexpress
  - game--grandmonsterslam--grandmonsterslam
  - game--harlequin1mb--harlequin1mb
  - game--heimdall--heimdall
  - game--heimdall2aga--heimdall2aga
  - game--helterskelter--helterskelter
  - game--heroquest&returnwitchlord--heroquest&returnwitchlord
  - game--heroquest2--heroquest2
  - game--hexumade--hexumade
  - game--hiredguns1mb--hiredguns1mb
  - game--historyline--historyline
  - game--historyline--historyline--intro
  - game--historyline--historyline--outro
  - game--hollywoodpokerpro--hollywoodpokerpro
  - game--hostages--hostages
  - game--hudsonhawk--hudsonhawk
  - game--ik+--ik+
  - game--impossamole--impossamole
  - game--indyheat--indyheat
  - game--international3dtennis--international3dtennis
  - game--internationaltennis--internationaltennis
  - game--interphase--interphase
  - game--ivanhoe--ivanhoe
  - game--jaguarxj220image--jaguarxj220image
  - game--jamespond--jamespond
  - game--jamespond2aga--jamespond2aga
  - game--jamespond3aga--jamespond3aga
  - game--jimpower--jimpower
  - game--judgedredd--judgedredd
  - game--k2401mb--k2401mb
  - game--katakis2disk--katakis2disk
  - game--kickoff--kickoff
  - game--kickoff&extratime2disk--kickoff&extratime2disk
  - game--kickoff216--kickoff216
  - game--kickoff2finalwhistle--kickoff2finalwhistle
  - game--kickoff2pluswc90--kickoff2pluswc90
  - game--kickoff2returntoeurope--kickoff2returntoeurope
  - game--kidchaos--kidchaos
  - game--killinggameshow--killinggameshow
  - game--kingsquest6--kingsquest6
  - game--landgenesisagacd--landgenesisagacd
  - game--leander--leander
  - game--ledstorm--ledstorm
  - game--lethalxcess--lethalxcess
  - game--lionheart--lionheart
  - game--liquidkidsimage--liquidkidsimage
  - game--logical--logical
  - game--logistic--logistic
  - game--lorna--lorna
  - game--lostpatrol--lostpatrol
  - game--lotus--lotus
  - game--lotus2--lotus2
  - game--lotus3--lotus3
  - game--magicpockets--magicpockets
  - game--masterblazer--masterblazer
  - game--mayafast--mayafast
  - game--mayafastfr--mayafastfr
  - game--mayafr--mayafr
  - game--megalomania--megalomania
  - game--megatyphoon--megatyphoon
  - game--menace--menace
  - game--metalmutant--metalmutant
  - game--midnightresistance--midnightresistance
  - game--mightybombjack--mightybombjack
  - game--montypythonsflycir--montypythonsflycir
  - game--moonstone--moonstone
  - game--mrnutz--mrnutz
  - game--muds--muds
  - game--narc--narc
  - game--narcopolice--narcopolice
  - game--nathanneverit--nathanneverit
  - game--nebulus2--nebulus2
  - game--nevermind--nevermind
  - game--newzealandstory--newzealandstory
  - game--nightshift--nightshift
  - game--ninjawarriors--ninjawarriors
  - game--nitro--nitro
  - game--northandsouthimage--northandsouthimage
  - game--nosecondprize--nosecondprize
  - game--odyssey--odyssey
  - game--offshorewarrior--offshorewarrior
  - game--onestepbeyond--onestepbeyond
  - game--operationthunderbolt--operationthunderbolt
  - game--operationwolf--operationwolf
  - game--pang--pang
  - game--panzakickboxing--panzakickboxing
  - game--paradroid901mb--paradroid901mb
  - game--parasolstars--parasolstars
  - game--persiangulfinferno--persiangulfinferno
  - game--pgatourgolf&tourdisk--pgatourgolf&tourdisk
  - game--playermanager--playermanager
  - game--populous&datadisks--populous&datadisks
  - game--populous&datadisks--populous&datadisks--tff
  - game--populous&datadisks--populous&datadisks--tpl
  - game--populousworldeditor--populousworldeditor
  - game--postmanpat--postmanpat
  - game--protennistour--protennistour
  - game--protennistour2--protennistour2
  - game--psyborg--psyborg
  - game--puggsy--puggsy
  - game--pushover--pushover
  - game--putty--putty
  - game--puttysquadaga--puttysquadaga
  - game--quartz--quartz
  - game--qwak--qwak
  - game--rainbowislands--rainbowislands
  - game--rallycrosschallenge--rallycrosschallenge
  - game--rbi2baseball--rbi2baseball
  - game--redheat--redheat
  - game--rickdangerous--rickdangerous
  - game--rickdangerous2--rickdangerous2
  - game--rickdangerous25--rickdangerous25
  - game--ringsofmedusa--ringsofmedusa
  - game--roadkillaga--roadkillaga
  - game--robinhoodlegendquest--robinhoodlegendquest
  - game--robocop--robocop
  - game--robocop3--robocop3
  - game--rocknroll--rocknroll
  - game--rockstaratemyhamster--rockstaratemyhamster
  - game--rodland--rodland
  - game--rtype2--rtype2
  - game--ruffntumble--ruffntumble
  - game--rygaraga--rygaraga
  - game--saintdragon--saintdragon
  - game--sarcophaser--sarcophaser
  - game--scoobydoo&scrappydoo--scoobydoo&scrappydoo
  - game--secondsamuraiaga--secondsamuraiaga
  - game--sevengatesofjambalaimage--sevengatesofjambalaimage
  - game--shadowlands--shadowlands
  - game--shadowofthebeast--shadowofthebeast
  - game--shadowofthebeast2--shadowofthebeast2
  - game--shadowofthebeast3--shadowofthebeast3
  - game--shadowwarriors--shadowwarriors
  - game--silkworm--silkworm
  - game--simonthesorcereraga--simonthesorcereraga
  - game--simulcra--simulcra
  - game--skidmarksaga--skidmarksaga
  - game--sleepwalkeraga--sleepwalkeraga
  - game--snowbrosimage--snowbrosimage
  - game--soccerkidaga--soccerkidaga
  - game--spaceharrier2--spaceharrier2
  - game--speedball2--speedball2
  - game--storiaancestrale--storiaancestrale
  - game--storiaancestrale--storiaancestrale--ch2
  - game--storiaancestrale--storiaancestrale--ch3
  - game--storiaancestrale--storiaancestrale--ch4
  - game--stuntcarracer--stuntcarracer
  - game--stuntcarracertnt--stuntcarracertnt
  - game--supercars2--supercars2
  - game--supercars2disk--supercars2disk
  - game--superherodemo--superherodemo
  - game--supersillyskidmarkscd--supersillyskidmarkscd
  - game--superskidmarks--superskidmarks
  - game--superskidmarks+cd--superskidmarks+cd
  - game--superskidmarksfyedcd--superskidmarksfyedcd
  - game--superstardustaga--superstardustaga
  - game--switchblade--switchblade
  - game--switchblade2--switchblade2
  - game--tensaidemo--tensaidemo
  - game--tfxaga--tfxaga
  - game--thunderhawkah73m--thunderhawkah73m
  - game--tinybobble--tinybobble
  - game--tinytroops--tinytroops
  - game--toki--toki
  - game--tony&friends--tony&friends
  - game--toobin--toobin
  - game--torvakthewarrior--torvakthewarrior
  - game--trapsntreasures--trapsntreasures
  - game--turrican--turrican
  - game--turrican2--turrican2
  - game--turrican3--turrican3
  - game--tusker--tusker
  - game--ufoenemyunknown--ufoenemyunknown
  - game--universe--universe
  - game--unrealntsc--unrealntsc
  - game--untouchables--untouchables
  - game--untouchablesse--untouchablesse
  - game--vaxine--vaxine
  - game--virocopaga--virocopaga
  - game--voyager--voyager
  - game--vroom&datadisk--datadisk
  - game--vroom&datadisk--vroom
  - game--vroommultiplayer--vroommultiplayer
  - game--walkerdecrunched--walkerdecrunched
  - game--warhead--warhead
  - game--warzonecoredesign--warzonecoredesign
  - game--warzoneparadox--warzoneparadox
  - game--waxworks--waxworks
  - game--westerngames--westerngames
  - game--wolfchild--wolfchild
  - game--worms2mb--worms2mb
  - game--wormsdcaga12mb--wormsdcaga12mb
  - game--yolandaimage--yolandaimage
  - game--zarathrusta--zarathrusta
  - game--zeewolf--zeewolf
  - game--zeewolf2--zeewolf2
  - game--zout--zout
  - game-notwhdl--brutalhomicide
  - game-notwhdl--poing
  - game-notwhdl--poing2
  - game-notwhdl--poing3
  - game-notwhdl--poing4
  - game-notwhdl--poing5
  - game-notwhdl--poing6
  - game-notwhdl--poing7
