--- # AGS2 Menu structure
- Test:
  - AirborneRanger
  - AlienBreedTA
  - AnotherWorldLostLevel
  - APBImage
  - ApidyaSpecialEdition
  - Astaroth
  - Atomix

  - Barbarian2Palace
  - BattleChess
  - BattleChess2
  - BeyondTheIcePalace
  - BiplaneDuel
  - BMXSimulator
  - BoneCruncherEnhanced
  - BrutalHomicide
  - BrutalHomicide2
  - BubbleAndSqueak

  - CadaverThePayoff
  - CannonSoccer
  - ChambersOfShaolin
  - ChuckRock
  - ChuckRock2
  - Civilization
  - ClownOMania
  - Colonization
  - CrystalDragon # Installer seems bodged now, it used to work fine.
  - CrystalKingdomDizzy
  - Cubulus

  - DeathSword
  - DizzyCollection--Disk1
  - DizzyCollection--Disk2
  - DizzysExcellentAdventures--Disk1
  - DizzysExcellentAdventures--Disk2
  - DuckTales
  - Dune

  - EMotion
  - EmeraldMine2
  - EmeraldMine3
  - EmeraldMine

  - FaeryTaleAdventure
  - FantasticDizzy
  - FantasyWorldDizzy
  - Fascination
  - FernandezMustDie
  - FinalAssault
  - FireForce
  - Firepower
  - FirstContact
  - Flink
  - FlyHarder
  - FlyingSharkSE
  - FormulaOneGrandPrix4Disk
  - Frenetic
  - Frontier
  - FrontierCD32
  - FuryOfTheFurries
  - FuryOfTheFurriesCD32
  - FutureTank
  - FutureWars
  - Fuzzball

  - GalacticTheXmasEdition
  - Gauntlet2
  - Gauntlet3
  - GemX
  - GhoulsNGhosts
  - Giana2
  - Giganoid
  - Globdule
  - Goal
  - Gobliiins
  - Gobliins2
  - Goblins3
  - Gods
  - Gods
  - GoldenAxe
  - GoofysRailwayExpress
  - GrandMonsterSlam
  - Gravity
  - GreatCourts
  - GreatCourts2
  - GreatGianaSisters
  - Gunship2000

  - Hammerfist
  - HardNHeavy
  - Harlequin
  - Heimdall
  - Heimdall2
  - HelterSkelter
  - HeroQuest
  - HeroQuest2
  - HexumaDe
  - Hillsfar
  - HiredGuns
  - Historyline
  - Historyline--Intro
  - HollywoodPokerPro
  - Hostages
  - HudsonHawk
  - Hunter
  - Hybris

  - IK+
  - IkariWarriors
  - Impossamole
  - ImpossibleMission2025
  - IndianaJonesAtlantisAct
  - IndianaJonesAtlantisAdv
  - IndianaJonesTempleOfDoom
  - Indianapolis500
  - IndyHeat
  - IndyJonesLastCrusAdv
  - InnocentUntilCaught
  - InsectsInSpace
  - International3DTennis
  - Interphase
  - ItCameFromTheDesert
  - ItCameFromTheDesert2
  - Ivanhoe

  - JaguarXJ220
  - JamesPond
  - JamesPond2
  - JamesPond2AGA # Is AGA version canonical?
  - JamesPond3
  - JamesPond3AGA # Is AGA version canonical?
  - JimmyWhitesSnooker
  - JimPower
  - JudgeDredd
  - JumpingJackSon
  - JungleStrike

  - K240
  - Katakis
  - Katakis2Disk
  - KickOff
  - KickOff&ExtraTime2Disk
  - KickOff2
  - KickOff216
  - KickOff2FinalWhistle
  - KickOff2ReturnToEurope
  - KidChaos
  - KidGloves
  - Kikstart2
  - KillingGameShow
  - KingOfChicago
  - Klax
  - KnightsOfTheCrystallion
  - Kristal
  - Kult

  - LamborghiniAmericanChllng
  - LandGenesis
  - Larrie
  - LaserSquad
  - LaserSquadNTSC
  - Leander
  - Leatherneck
  - LEDStorm
  - LegendOfFaerghailNTSC
  - LegendOfKyrandia
  - LeisureSuitLarry3
  - Lemmings
  - Lemmings2
  - LemmingsHoliday1993
  - LemmingsHoliday1994
  - LemmingsNewYear9192
  - LemmingsXmasDemo1991
  - LemmingsXmasDemo1992
  - LethalXcess
  - LightCorridor
  - Lionheart
  - LiquidKids
  - Llamatron
  - Logical
  - Logistic
  - Loom
  - Lorna
  - LostPatrol
  - LostTreasuresOfInfocom
  - LostVikings
  - Lotus
  - Lotus2
  - Lotus3

  - MagiclandDizzy
  - MagicPockets
  - ManiacMansion
  - MarbleMadness
  - Masterblazer
  - Maya
  - MegaLoMania
  - MegaTyphoon
  - Menace
  - Mercenary
  - Mercenary3
  - MetalLaw
  - MetalMutant
  - MFTanks
  - MidnightResistance
  - Midwinter
  - Midwinter2
  - MiG29Fulcrum
  - MightyBombJack
  - Millennium22
  - MindWalker
  - MonkeyIsland2
  - MontyPythonsFlyCir
  - Moonstone

  - MrNutz
  - MUDS
  - Murder
  - Narc
  - NarcoPolice
  - NathanNever
  - NaughtyOnes
  - Nebulus
  - Nebulus2
  - Neuromancer
  - NeverMind
  - NewZealandStory
  - NightShift
  - NinjaRemix
  - NinjaWarriors
  - Nitro
  - NorthAndSouth
  - NoSecondPrize
  - NuclearWar

  - Oath
  - Obliterator
  - Obsession
  - Odyssey
  - OffShoreWarrior
  - OhNoMoreLemmings
  - OilImperium
  - OneStepBeyond
  - OperationCleanstreets
  - OperationStealth
  - OperationThunderbolt
  - OperationWolf
  - Oxxonian

  - PacLand
  - Pacmania
  - Pandora
  - Pang
  - PanzaKickBoxing
  - Paradroid90
  - ParaglidingSimulation
  - ParasolStars
  - Perihelion
  - PersonalNightmare
  - PGAEuropeanTour
  - PGATourGolf
  - Phantasie3
  - PinballDreams
  - PinballFntsies
  - PinballIllusions
  - PinballPrelude
  - PioneerPlague
  - PipeDream
  - Pirates
  - Platoon
  - PlayerManager
  - PlayerManager2
  - PlayerManager2ExtraAGA
  - Plotting
  - Pod
  - Poing
  - Poing2
  - Poing3
  - Poing4
  - Poing5
  - Poing6
  - Poing7
  - Populous
  - Populous&DataDisks
  - Populous2&ChallengeGames
  - PortsOfCall
  - PostmanPat
  - Powermonger
  - PowermongerWW1Edition
  - Premiere
  - PrinceOfPersia
  - Project1
  - ProjectXSE
  - ProjectXSE2017
  - Projectyle
  - ProTennisTour
  - ProTennisTour2
  - Psyborg
  - PuffysSaga
  - Puggsy
  - PurpleSaturnDay
  - PushOver
  - Putty
  - PuttySquad
  - Puzznic

  - Qix
  - Quartz
  - Questron2
  - Qwak

  - Racter
  - RailroadTycoon
  - RainbowIslands
  - RallyCrossChallenge
  - Rampart
  - RanX
  - RBI2Baseball
  - Realms
  - RedHeat
  - RedStormRising
  - Renegade
  - Renegades
  - Resolution101
  - RevengeOfMutantCamels
  - RevengeOfMutantCamels2
  - RickDangerous
  - RickDangerous2
  - RickDangerous25
  - RingsOfMedusa
  - RiseOfTheDragon
  - Roadkill
  - RoadwarEuropa
  - RobinHoodLegendQuest
  - RoboCop
  - RoboCop3
  - RocketRanger
  - RockNRoll
  - RockStarAteMyHamster
  - RodLand
  - Rogue
  - Rotox
  - RType
  - RType2
  - RuffNTumble
  - RygarAGA

  - SaintDragon
  - Sarcophaser
  - ScoobyDoo&ScrappyDoo
  - SecondSamurai
  - SecretOfMonkeyIsland
  - SensibleGolf
  - SensibleSoccer1MB
  - SensibleWorldOfSoccer9697
  - Sentinel
  - Settlers
  - SevenGatesOfJambala
  - ShadowFighter
  - Shadowlands
  - ShadowOfTheBeast
  - ShadowOfTheBeast2
  - ShadowOfTheBeast3
  - ShadowWarriors
  - Shanghai
  - ShaqFu
  - ShockWave
  - ShufflepuckCafe
  - SideWinder
  - SideWinder2
  - Silkworm
  - SillyPutty
  - SimAntHiRes
  - SimCity
  - SimonTheSorcererAGA
  - Simulcra
  - Sinbad
  - Skidmarks
  - SlamTilt
  - Sleepwalker
  - SlySpySecretAgent
  - SnowBros
  - SoccerKid
  - Spaceball
  - SpaceCrusade&VoyageBeyond
  - SpaceHarrier2
  - Spaceport
  - SpaceTaxi3
  - Speedball
  - Speedball2
  - SperisLegacy
  - SpindizzyWorlds
  - SpittingImage
  - Springtime
  - SpyVsSpy
  - SpyVsSpy2TheIslandCaper
  - SpyVsSpy3ArcticAntics
  - SpyWhoLovedMe
  - Starblaze
  - Starglider
  - Starglider2
  - Statix
  - StreetRod
  - StreetRod2
  - StuntCarRacer
  - StuntCarRacerTNT
  - SuperCars
  - SuperCars2
  - Superfrog
  - SuperGemZ
  - SuperGridRunner
  - SuperHangOn
  - SuperHero
  - SuperMethaneBros
  - SuperOffRoad
  - SuperScrambleSimulator
  - SuperSkidmarks
  - SuperSkidmarks+CD
  - SuperSkweek
  - SuperStardust
  - SuperTwintris
  - SuprTennisChmps
  - Switchblade
  - Switchblade2
  - SWIV
  - SwordOfSodan
  - Syndicate
  - SyndicateAmericanRevolt

  - TeenageQueen
  - TempleOfApshaiTrilogy
  - Tensai
  - Terramex
  - TestDrive2
  - TetrisMirrorsoft
  - TetrisPro
  - TFX
  - TheirFinestHour
  - ThemePark
  - ThreeStooges
  - Thunderbirds
  - ThunderHawkAH73M
  - TinyTroops
  - TitusTheFox
  - Toki
  - TomAndTheGhost
  - Tony&Friends
  - Toobin
  - TorvakTheWarrior
  - TotalEclipse
  - TotalRecall
  - TowerOfBabel
  - TrapsNTreasures
  - TreasureIslandDizzy
  - TreasureTrap
  - TrexWarrior
  - TurboRaketti2Fi
  - Turrican
  - Turrican2
  - Turrican3
  - Tusker
  - TVSportsBasketball
  - TVSportsFootball
  - Twintris
  - TwinWorld
  - TyphoonThompson


  - Uridium2 # PAL5, but can't get it to stick. Caused by Graftgold logo screen?

  - Vyrus

  - WindowWizard # Loads a screen with some pixels in the middle, then stops

  
  
  - YoJoe
  - Yolanda
  - YolandaImage

  - ZakMcKracken
  - ZanyGolf
  - Zarathrusta
  - Zeewolf
  - Zeewolf2
  - Zool
  - ZOut
