--- # AGS2 Menu structure
- Test:
  - game--arabiannights--arabiannights
  - game--awesome--awesome
  - game--batmanthemovie2disk--batmanthemovie2disk
  - game--blastar--blastar
  - game--bonecruncher--bonecruncher
  - game--bonecruncherenhanced--bonecruncherenhanced
  - game--crystaldragon--crystaldragon # still doesn't launch
  - game--dangerfreak--dangerfreak # Lots of gfx corruption
  - game--fireandicecd32--fireandicecd32  
  - game--fire&icexmasdemo--fire&icexmasdemo
  - game--flashback--flashback
  - game--international3dtennis--international3dtennis
  - game--internationaltennis--internationaltennis
  - game--jimpower--jimpower
  - game--katakis2disk--katakis2disk # Never gets past asking for data disk
  - game--kidchaos--kidchaos
  - game--landgenesisagacd--landgenesisagacd
  - game--supercars2--supercars2

  - game--tensaidemo--tensaidemo
  - game--tfxaga--tfxaga
  - game--thunderhawkah73m--thunderhawkah73m
  - game--tinybobble--tinybobble
  - game--tinytroops--tinytroops
  - game--toki--toki
  - game--tony&friends--tony&friends
  - game--toobin--toobin
  - game--torvakthewarrior--torvakthewarrior
  - game--trapsntreasures--trapsntreasures
  - game--turrican--turrican
  - game--turrican2--turrican2
  - game--turrican3--turrican3
  - game--tusker--tusker
  - game--ufoenemyunknown--ufoenemyunknown
  - game--universe--universe
  - game--unrealntsc--unrealntsc
  - game--untouchables--untouchables
  - game--untouchablesse--untouchablesse
  - game--vaxine--vaxine
  - game--virocopaga--virocopaga
  - game--voyager--voyager
  - game--vroom&datadisk--datadisk
  - game--vroom&datadisk--vroom
  - game--vroommultiplayer--vroommultiplayer
  - game--walkerdecrunched--walkerdecrunched
  - game--warhead--warhead
  - game--warzonecoredesign--warzonecoredesign
  - game--warzoneparadox--warzoneparadox
  - game--waxworks--waxworks
  - game--westerngames--westerngames
  - game--wolfchild--wolfchild
  - game--worms2mb--worms2mb
  - game--wormsdcaga12mb--wormsdcaga12mb
  - game--yolandaimage--yolandaimage
  - game--zarathrusta--zarathrusta
  - game--zeewolf--zeewolf
  - game--zeewolf2--zeewolf2
  - game--zout--zout
  - game-notwhdl--brutalhomicide
  - game-notwhdl--poing
  - game-notwhdl--poing2
  - game-notwhdl--poing3
  - game-notwhdl--poing4
  - game-notwhdl--poing5
  - game-notwhdl--poing6
  - game-notwhdl--poing7
