--- # AGS2 Menu structure
- Test:
  - CannonFodder
  - CrystalHammerV2
  - Defender2
  - DefenderOfTheCrown
  - DesertStrike
  - Hybris
  - Settlers
- TestWS:
  - note: Widescreen demos
  - Andromeda-Rule30: { scale: 6, v_offset: 48 }
  - BaygonAGA: Melon!
  - BrunosMusicBox3: { v_offset: 4 }
  - Coma: { note: COMA! }
  - Nested:
    - How2SkinACat
    - Delphine-Collection: { unavailable: True }
    - HumanTarget
    - Interference
