--- # AGS2 Menu structure
- Test:
  - game--crystaldragon--crystaldragon # still doesn't launch
  - game--dangerfreak--dangerfreak # Lots of gfx corruption
  - game--katakis2disk--katakis2disk # Never gets past asking for data disk
