--- # AGS2 Menu structure
- Done:
  - 3DGalax
  - 3001OConnorsFight

  - ActionFighter
  - AddamsFamily
  - AdventuresOfQuik&Silva
  - AgonyNTSC
  - AirSupportNTSC
  - Akira
  - Alcatraz
  - Alianator
  - AlienBreed
  - AlienBreed2AGA
  - AlienBreedSpecialEdition
  - AlienDrugLords
  - AllNewWorldOfLemmingsAGA
  - AllTerrainRacing
  - AlphaWaves
  - AlteredDestiny
  - Ambermoon
  - Amegas
  - Amiganoid
  - Amnios
  - AnotherWorld
  - ApidyaKaiko
  - Apprentice
  - AquaticGames
  - AquaventuraNTSC
  - ArabianNights
  - ArcadePoolAGA
  - ArcherMacLeansPool
  - ArchipelagosNTSC
  - ArkanoidNTSC
  - ArkanoidRevengeOfDoh
  - Assassin
  - AssassinSpecialEdition
  - ATF2
  - AtominoNTSC
  - Awesome
  - AxelsMagicHammer

  - BadCat
  - BadCompany
  - BadLands
  - BalanceOfPower1990Ed
  - Ballistix
  - Banshee
  - BaseJumpers
  - BatmanCapedCrusader
  - BatmanTheMovie
  - BattleCommand
  - BattleIsle
  - BattleSquadronNTSC
  - Battletech
  - BCKid
  - BeachVolley
  - BeneathAStlSky
  - Benefactor
  - BestOfTheBest
  - BigRun
  - BillsTomatoGameNTSC
  - BioChallenge
  - BionicCommando
  - BlackCrypt
  - BladeWarrior
  - Blastar
  - Blasteroids
  - Blob
  - BloodMoney
  - BloodNet
  - Bobo
  - BodyBlows
  - BombJack
  - Bombuzal
  - Botics
  - BrandsHatch
  - BrianTheLion
  - BubbaNStix
  - BubbleBobble
  - Budokan
  - BuggyBoy
  - Builderland
  - BundesligaMngrHatt

  - Cabal
  - Cadaver
  - CadaverThePayoff
  - CaliforniaGames
  - CannonFodder
  - CannonFodder2
  - CannonFodder2AlienLevels
  - CannonFodderCD32
  - CannonFodderNewCampaign
  - CannonFodderPlus
  - Captive
  - CardiaxxTeam17
  - CaribbeanDisasterDe
  - CarlLewisChallenge
  - Carnage
  - CarrierCommand
  - CarVup
  - CastleMaster
  - CastleMaster2
  - CastleWarrior
  - CelticLegends
  - Centurion
  - ChaosEngine
  - ChaosEngine2
  - CircusAttractions
  - Civilization
  - ClikClak
  - Colony
  - CrazySue
  - CrazySueGoesOn
  - CruiseForACorpse
  - CrystalHammerV2
  - CurseOfEnchantia
  - Cybercon3
  - Cyberpunks
  - Cytron

  - Damocles
  - Darkmere
  - DarkSeed
  - DarkSeedCD32
  - Datastorm
  - Defender2
  - DefenderOfTheCrown
  - Deflektor
  - DejaVu
  - DejaVu2LostInLasVegas
  - Denaris
  - DesertStrike
  - Deuteros
  - DeviousDesigns
  - DGeneration
  - DisposableHero
  - DistantArmies
  - DogsOfWar
  - DojoDan
  - DownhillChallenge
  - DragonBreed
  - DragonStrike
  - DreamWeb
  - DrivinForce
  - Dune2
  - DungeonMaster
  - DynaBlaster
  - Dyter07

  - Ebonstar
  - Eco
  - Elfmania
  - Elite
  - Elvira
  - Elvira2
  - EMotion
  - EmpireStrikesBack
  - EmpireSoccer94
  - Epic
  - EscapeFTPOTRobotMonsters
  - Extase
  - Exterminator
  - EyeOfTheBeholder
  - EyeOfTheBeholder2
  - EyeOfTheBeholder2AGA
  - EyeOfTheBeholderAGA

  - F15StrikeEagle2
  - F19StealthFighter
  - F29Retaliator
  - FA18Interceptor
  - Falcon
  - FateGatesOfDawn
  - FinalBlow
  - FinalCountdown
  - FireAndBrimstone
  - FireAndIce
  - FirstSamurai
  - Flashback
  - FlightOfTheAmazonQueen
  - Flood
  - Floor13
  - FourCrystalsOfTrazere

  - ItCameFromTheDesert
  - ItCameFromTheDesert2

  - SensibleGolf
  - SensibleSoccer
  - SensibleSoccer9293
  - SensibleSoccerBulldogBlty
  - SensibleSoccerEuro
  - SensibleTrainSpotting
  - SensibleWorldMoonSoccer
  - SensibleWorldOfSoccer
  - SensibleWorldOfSoccer9596
  - SensibleWorldOfSoccer9697
  - StoriaAncestrale

  - TeenageQueen # PAL60
  - TempleOfApshaiTrilogy # NTSC
  - Tensai # 20 PAL5
  - Terramex # PAL60
  - TestDrive2 # NTSC
  - TetrisMirrorsoft # NTSC
  - TetrisPro # PAL
  - TheirFinestHour # NTSC
  - ThemePark # NTSC
  - ThreeStooges # NTSC
  - Thunderbirds # PAL60
  - ThunderHawkAH73M # -2 PAL5
  - TinyTroops # PAL
  - TitusTheFox # PAL60
  - Toki # 14 PAL5
  - TomAndTheGhost # PAL60
  - Tony&Friends # 2 PAL5
  - Toobin # 5 PAL5
  - TorvakTheWarrior # PAL60
  - TotalEclipse # NTSC
  - TotalRecall #PAL60
  - TowerOfBabel # PAL60
  - TrapsNTreasures # PAL
  - TreasureIslandDizzy # PAL60
  - TreasureTrap # PAL60
  - TrexWarrior # PAL
  - TurboRaketti2Fi # PAL
  - Turrican # 4 PAL5
  - Turrican2 # 4 PAL5
  - Tusker # 30 PAL5
  - TVSportsBasketball # NTSC
  - TVSportsFootball # NTSC
  - Twintris # PAL 
  - TwinWorld # 10 PAL5
  - TyphoonThompson # NTSC

  - UFOEnemyUnknown # 30 PAL5 (British developer, music sounds correct in PAL)
  - Ugh # PAL
  - Ultima5 # NTSC
  - Universe 
  - Unreal # 24 (NTSC)
  - Untouchables # 20 PAL5
  - Uridium2 # PAL60 (Shoot'em up)
  
  - Vaxine # 4 PAL5
  - VenusTheFlytrap 
  - VirocopAGA # 21 PAL5
  - Virus
  - Voyager # 22 PAL5
  - Vroom # -2 PAL5
  - Vyrus # PAL60 (European developer, but shoot'em-up)

  - Walker # -3 PAL5
  - WalkerDecrunched # Is Decrunched canonical? More samples? (applied PAL5 to all)
  - Warhead # -2 PAL5
  - WarInMiddleEarth # NTSC
  - WarzoneCoreDesign # 6 PAL5
  - Waxworks # 26 PAL5
  - WCLeaderBoard # NTSC
  - WeirdDreams # NTSC
  - WesternGames # 5 PAL5
  - WIEuropeIsCarmenSandiego # NTSC
  - Wings # NTSC
  - WingsOfDeath # PAL60
  - WingsOfFury # NTSC
  - WizNLiz # Actual PAL
  - WITUSAIsCarmenSandiego # NTSC
  - WITWIsCarmenSandiego # NTSC
  - Wizball # 14 PAL5
  - Wizkid # Actual PAL (although with large margins?)
  - Wolfchild # 2 PAL5
  - WorldGames # NTSC
  - Worms2MB # -32 (PAL)
  - WormsDCAGA12MB # -10 (PAL)
  
  - Xenon # NTSC
  - Xenon2 # 16 PAL5 (sadly, music is too fast in NTSC)
  - XOut # PAL60
  - XOut2Disk # PAL60
  - Xybots # PAL60
  
  - YoJoe # PAL60 (makes the artwork look correct, also Hudson Soft)
  - Yolanda # -2 PAL5

  - ZakMcKracken # NTSC
  - ZanyGolf # NTSC
  - Zarathrusta # 1 PAL5
  - Zeewolf # PAL60
  - Zeewolf2 # # PAL60
  - Zool # PAL
  - ZOut # 12 PAL5 (but seems to only stretch in the vertical direction?)

  
