- All Time Favorites:
  - note: Seminal, or otherwise significant, releases according to 1.000.000 BOYS aka Megaboys.
  - FisherhawkDr
  - JulietCase-CCCP
  - MeganeRellu

- Coding Challenges:
  - note: Coding challenges posed to the scene.
  - Checkerboard Challenge:
    - note: Zooming checkerboard challenge at GERP 2018.
    - Loonies-MyLuckyNumber
    - Oxyron-LordsOfTheBoards
  - Rubber Cube Challenge:
    - note: The rubber cube challenge of 2014.
    - Lemon-NatsuNoGomu
    - Loonies-Octorubber
