- Hall of Fame:
  - rank: 1
  - note: Seminal, or otherwise significant, releases according to 1.000.000 BOYS aka Megaboys.
  - image: { ops: { op: "pi", path: "top/hall_of_fame.png" }, size: [320, 128], scale: [1, 1] }
  - 3DDemo2
  - Abyss-Coda
  - AbyssDone
  - Arte
  - BatmanVuelve
  - BaygonAGA
  - BrunosMusicBox3
  - Coma
  - CopperMaster
  - Cryptoburners-BrainState
  - Darkroom
  - DayOfReckoning
  - DesertDream
  - Drugstore
  - EndlessPiracy-Scrabble
  - Enigma
  - Extension
  - FisherhawkDr
  - FridayAtEightAGA
  - FullmoonAGA
  - Hardwired
  - HisMastersNoise
  - Hologon
  - How2SkinACat
  - HumanTarget
  - Interference
  - Interparallactic
  - InTheKitchen
  - Joyride
  - JulietCase-CCCP
  - KanaalinarVoitus
  - KayraSoiro
  - Lemon-Colombia
  - LostWorld
  - MajorRelease
  - MaximumVelocity
  - MegademoBudbrain
  - MegademoNorthStar
  - Megademo3NSFLT
  - MegademoRedSectorInc
  - MeganeRellu
  - Melon-Tetris
  - MentalHangover
  - MonoMeno66
  - MusicDisk3DMob
  - Nexus7AGA
  - NumbAGA
  - ParadoxFutureBike
  - Paranoimia-AnotherCrack
  - Paranoimia-Turicon
  - Paranoimia-XOut
  - PlanetMAGA
  - RedSector-Plutos
  - RinkADinkRedux
  - Roots2AGA
  - Sequential
  - ShinobiIntro
  - SOS--SOS
  - Spaceballs-Emperor
  - Spaceballs-Makt
  - Spaceballs-Peek
  - Stateline
  - Stellar-Bananamen
  - TechnologicalDeath
  - TechTech
  - TerminalFuckup
  - UnitA FA18Interceptor
  - VectorDemoTristanLorach
  - VirtualDreams-ChaosLand
  - WorldOfCommodore

- Coding Challenges:
  - note: Coding challenges posed to the scene.
  - Checkerboard Challenge:
    - note: Zooming checkerboard challenge at GERP 2018.
    - Loonies-MyLuckyNumber
    - Oxyron-LordsOfTheBoards
    - TEK-Deadline2018Inv
    - Tulou-ExclusiveGalore
  - Rubber Cube Challenge:
    - note: The rubber cube challenge of 2014.
    - Lemon-NatsuNoGomu
    - Loonies-Octorubber
    - Spaceballs-Dubzilla
    - Spaceballs-Rubzilla
