- Spotlight:
  - rank: 2
  - note: More great or interesting demos, sorted by year.
  - image: { ops: { op: "pi", path: "top/spotlight.png" }, size: [320, 128], scale: [1, 1] }
  - "1988":
    - image: { op: "tx", txt: "’88", size: 190 }
    - Megademo2Northstar
    - MegademoNorthstar
    - MegaloDemos

  - "1989":
    - image: { op: "tx", txt: "’89", size: 190 }
    - MegademoRedSectorInc
    - Megademo7Kefrens
    - MegademoJoy&MGf&TJC
    - Megademo3NSFLT
    - MegademoPhenomena

  - "1990":
    - image: { op: "tx", txt: "’90", size: 190 }
    - Animotion
    - CeBIT90
    - Coma
    - CopperMaster
    - FollowMe
    - Highway1930
    - Megademo2Budbrain
    - Megademo2Rebels
    - Megademo8Kefrens
    - MegademoBudbrain
    - MegademoHumanoids
    - MegademoIntuition
    - MentalHangover
    - ObviousDisaster
    - TropicalSunset
    - WaterProof

  - "1991":
    - image: { op: "tx", txt: "’91", size: 190 }
    - Analogia
    - DecayingParadise
    - Elysium
    - Enigma
    - GlobalTrash
    - GuardianDragon
    - Hardwired
    - Joyride
    - OurDefOfBoombastic
    - Overdose
    - PlasticPassion
    - SeeingIsBelieving
    - VectorDemoTristanLorach
    - VoyageRazor1911

  - "1992":
    - image: { op: "tx", txt: "’92", size: 190 }
    - 3DDemo2
    - DayOfReckoning
    - DOS
    - GuardianDragon2
    - Hallucinations&Dreams
    - HumanTarget
    - InTheKitchen
    - JesusOnEs
    - KrestMassLeftovers
    - MaximumVelocity
    - Melon-Tetris
    - PointBlank
    - Punisher
    - SOS
    - SoundVision
    - Stateline
    - StateOfTheArt
    - WickedSensation
    - WorldOfCommodore

  - "1993":
    - image: { op: "tx", txt: "’93", size: 190 }
    - A.S.S
    - Aquarium
    - Arte
    - Balance-CuttingEdge
    - DemonDownload
    - DesertDream
    - EmptyheadAGA
    - Extension
    - FullmoonAGA
    - Groovy
    - How2SkinACat
    - Interference
    - LEGO-TheReal40K
    - Melon-GuruMeditation
    - MinaOmistanAGA
    - NotAGAin
    - NumbAGA
    - ProSIAK
    - Rednex-Revival
    - RinkADink
    - SozzledSomersault
    - Stellar-Bananamen
    - TechnologicalDeath
    - TerminalFuckup
    - VirtualDreams-ChaosLand

  - "1994":
    - image: { op: "tx", txt: "’94", size: 190 }
    - Cryptoburners-BrainState
    - Darkroom
    - Demo--Rampage
    - FridayAtEightAGA
    - Gevalia
    - JulietCase-CCCP
    - Melon-AcidTrip
    - Melon-Booo2
    - Movement-RastaBars
    - Nexus7AGA
    - RealAGA
    - Roots2AGA
    - SAGA
    - Sequential

  - "1995":
    - image: { op: "tx", txt: "’95", size: 190 }
    - Artwork-Dawn
    - Axis-Headcase
    - Axis-Siesta
    - BatmanVuelve
    - BaygonAGA
    - Drugstore
    - LoveAGA
    - PlanetMAGA

  - "1996":
    - image: { op: "tx", txt: "’96", size: 190 }
    - Rednex-DMA
    - Movement-Bubblegum
    - Sonik-Pure

  - "1997":
    - image: { op: "tx", txt: "’97", size: 190 }
    - Jormas-MonoMeno66

  - "1998":
    - image: { op: "tx", txt: "’98", size: 190 }
    - ElectronsAtWork

  - "2004":
    - image: { op: "tx", txt: "’04", size: 190 }
    - Jormas-MajorRelease

  - "2006":
    - image: { op: "tx", txt: "’06", size: 190 }
    - RNO-Fruitcake
    - UpRough-ShadowFighter

  - "2009":
    - image: { op: "tx", txt: "’09", size: 190 }
    - Jormas-MeganeRellu

  - "2012":
    - image: { op: "tx", txt: "’12", size: 190 }
    - RNO&Ghostown-BoogieTown
    - ScoopexUTSonix

  - "2013":
    - image: { op: "tx", txt: "’13", size: 190 }
    - RinkADinkRedux
    - Spaceballs-Straff
    - UpRough-15YearsOfFame

  - "2014":
    - image: { op: "tx", txt: "’14", size: 190 }
    - MoodsPlateau-SolveEtCoagula
    - Spaceballs-Emperor

  - "2015":
    - image: { op: "tx", txt: "’15", size: 190 }
    - Dekadence-Eighteen
    - Ghostown-SushiBoyz
    - Interparallactic
    - Jormas-HapyCarva72
    - Jormas-KayraSoiro

  - "2016":
    - image: { op: "tx", txt: "’16", size: 190 }
    - BombDreamdealersSanity-E255
    - Pacific-Koobz

  - "2017":
    - image: { op: "tx", txt: "’17", size: 190 }
    - Jormas-KanaalinArvoitus
    - Lemon+TDL-BlastFromThePast
    - Pacific-Monomateria
    - Spaceballs-Makt

  - "2018":
    - image: { op: "tx", txt: "’18", size: 190 }
    - Lemon+TDL-TheFall
    - Lemon-Lemonade
    - Spaceballs-Peek

  - "2019":
    - image: { op: "tx", txt: "’19", size: 190 }
    - Abyss-Coda
    - Deadliners-Five
    - DHS-CopperKaahBaahYaah
    - Offence-AHymnToHipparchus
    - TEK-FutureOfLimits

  - "2020":
    - image: { op: "tx", txt: "’20", size: 190 }
    - Hologon
    - Lemon-Colombia
    - Offence-TowardsDarkerTimes
    - Retream-TheCure

  - "2021":
    - image: { op: "tx", txt: "’21", size: 190 }
    - Andromeda-Rule30
    - Melon-Cortez
    - Melon-FisherhawkDr

  - "2022":
    - image: { op: "tx", txt: "’22", size: 190 }
    - AbyssBitmapRasters
    - AbyssDone
    - BatmanGroup-Posadas2022
    - FFPUnicodeAttac
    - Fnuque-HexJunkie
    - Koney-Ketamuskolar

  - "2023":
    - image: { op: "tx", txt: "’23", size: 190 }
    - DaltonMarkFerrari
    - Ghostown-Electric
