- Focus:
  - note: Lists curated with specialized theme or focus.
  - image: { ops: { op: "pi", path: "top/focus.png" }, size: [320, 128], scale: [1, 1] }
  - Amiga Exclusives:
    - note: A selection of games exclusive to the Amiga platform.
    - Agony
    - Akira
    - AllTerrainRacing
    - Ambermoon
    - Amegas
    - Amnios
    - Apidya
    - Aquaventura
    - ArabianNights
    - AssassinSpecialEdition
    - Banshee
    - BaseJumpers
    - Benefactor
    - BillsTomatoGame
    - BlackCrypt
    - Blob
    - BrianTheLion
    - CardiaxxTeam17
    - ChaosEngine2
    - CrazySueGoesOn
    - Cyberpunks
    - Cytron
    - Darkmere
    - Datastorm
    - DisposableHero
    - DojoDan
    - Ebonstar
    - Elfmania
    - FA18Interceptor
    - FinalCountdown
    - Fuzzball
    - Globdule
    - HeroQuest2
    - Hybris
    - ImpossibleMission2025
    - ItCameFromTheDesert2
    - K240
    - KidChaos
    - KnightsOfTheCrystallion
    - Lionheart
    - MindWalker
    - MrNutz
    - NathanNever
    - NaughtyOnes
    - NeverMind
    - Oath
    - OperationCleanstreets
    - ParaglidingSimulation
    - Perihelion
    - PioneerPlague
    - Premiere
    - Roadkill
    - RuffNTumble
    - ShadowOfTheBeast3
    - Skidmarks
    - SperisLegacy
    - SphericalWorlds
    - SpringTime
    - Superfrog
    - TinyTroops
    - TrapsNTreasures
    - Uridium2
    - Virocop
    - Walker
    - Wings
    - WormsDC
    - Zarathrusta
    - Zeewolf
  - Cyberpunk:
    - note: A selection of cyberpunk themed games.
    - BeneathAStlSky
    - BloodNet
    - DGeneration
    - DreamWeb
    - Extase
    - HiredGuns
    - Interphase
    - Neuromancer
    - RiseOfTheDragon
    - Syndicate
  - Deep Cuts:
    - note: Dare we say hidden gems?
    - AlphaWaves
    - BladeWarrior
    - DGeneration
    - GalacticTheXmasEdition
    - LaserSquad
    - MegaLoMania
    - MindWalker
    - Psyborg
    - TyphoonThompson
  - Esoteric:
    - note: A look in the obscure, sometimes incomprehensible, corners of the Amiga library.
    - 3001OConnorsFight
    - AlienDrugLords
    - Archipelagos
    - Colony
    - Eco
    - KnightsOfTheCrystallion
    - Kristal
    - Mercenary3
    - MindWalker
    - PioneerPlague
    - PurpleSaturnDay
    - Racter
    - Sentinel
    - Sinbad
    - TowerOfBabel
    - WeirdDreams
  - French Touch:
    - note: The French Amiga studios developed a distinct style, heavily influenced by domestic comics and easy access to manga and anime.
    - AnotherWorld
    - AnotherWorldLostLevel
    - BargonAttack
    - BeachVolley
    - Billiards2Simulator
    - BioChallenge
    - CaptainBlood
    - Extase
    - Fascination
    - FuryOfTheFurries
    - FutureWars
    - Geisha
    - GNius
    - Hostages
    - Ivanhoe
    - Kult
    - LiquidKids
    - Lorna
    - MaupitiIsland
    - MetalMutant
    - NorthAndSouth
    - OperationStealth
    - PanzaKickBoxing
    - PurpleSaturnday
    - RanX
    - Targhan
    - TeenageQueen
  - Good Arcade Conversions:
    - note: Steer clear of US Gold and there's some decent to good arcade conversions in the Amiga library.
    - Arkanoid
    - BombJackBeerEdition
    - BubbleBobble
    - BuggyBoy
    - EmpireStrikesBack
    - MarbleMadness
    - NewZealandStory
    - NinjaWarriors
    - Pang
    - RainbowIslands
    - RodLand
    - RType
    - Rygar
    - Silkworm
    - SnowBros
    - SuperOffRoad
    - TinyBobble
  - Hacks:
    - note: While not as plentiful as on console platforms, "ROM" hacks and improvements exist on Amiga too.
    - AnotherWorldLostLevel
    - ApidyaSpecialEdition
    - Area88
    - BoneCruncherEnhanced
    - EyeOfTheBeholder2AGA
    - EyeOfTheBeholderAGA
    - FlyingSharkSE
    - Giana2
    - MoreLemmings
    - ProjectXSE2017
    - SWOS2020
    - SWOS2021
    - SWOS2122
    - StuntCarRacerTNT
    - SuperCars2AGA
    - TestDrive2&DataDisksNGC
    - Tony&Friends
    - Turrican2AGA
    - UntouchablesSE
  - Licensed Games:
    - note: Surprisingly playable or interesting games based on licensed IP.
    - AddamsFamily
    - BatmanCapedCrusader
    - BatmanTheMovie
    - HudsonHawk
    - RoboCop3
    - ScoobyDoo&ScrappyDoo
    - TotalRecall
  - PD Golden Age:
    - note: The golden age of Amiga public domain, shareware, freeware, beerware, etc.
    - ActOfWar
    - AerialRacers
    - AlienBash2
    - AlienFishFinger
    - AmoebaInvaders
    - BoulderdashC64
    - Breed96
    - Cybernetix
    - DeluxeGalagaAGA
    - DeluxePacmanAGA
    - Drip
    - JellyOthelly
    - KastleKumquat
    - Llamatron512KB
    - MegaBallAGA
    - Microbes
    - MineRunner
    - MissilesOverXerion
    - MortonStrikesBackAGA
    - MotorolaInvaders2AGA
    - NibbyNibble
    - PlatMan
    - Poing7
    - Poweroids
    - R3ArtOfRocketry
    - ScorchedTanks
    - SpaceTaxi3
    - SpringTime
    - StarTrekTR
    - SuperFoulEgg
    - SuperObliteration
    - Tetren
    - Transplant
  - PD Silver Age:
    - note: The silver age of Amiga public domain games is now, apparently!
    - BlockySkies
    - Boxx4
    - CenterCourt2AGA
    - CurseOfRabenstein
    - Enemy2MissingInAction
    - FredsJourney
    - HamuletDemo
    - IncaMan
    - KiwiTale
    - Landfill
    - LUMA
    - MariaRenardsRevenge
    - Roguecraft
    - SkillGrid
    - SmartyAndTheNastyGluttons
    - SolidGold
    - Tenebra2
    - TinyBobble
    - Tinyus
    - TrapRunner
    - WrongWayDriver
    - Zerosphere
  - Spanish Conquistadors:
    - note: Spain was the 2nd largest 8-bit game producer in Europe in 1983 to 1992. These later titles were infamous for being pretty but tough.
    - AfterTheWar
    - AncientArtOfWar
    - AstroMarineCorps
    - Corsarios
    - GrandPrixMaster
    - HammerBoy
    - Livingstone2
    - Lorna
    - MegaPhoenix
    - Mot
    - NarcoPolice
    - NavyMoves
    - RiskyWoods
    - Satan
    - SolNegro
    - ViajeAlCentroDelaTierraEs
  - Tour de Force:
    - note: Games that pushed the Amiga to its limits.
    - ApanoSin
    - BrianTheLion
    - DrivinForce
    - Elfmania
    - JimPower
    - KidChaos
    - Leander
    - Lionheart
    - MrNutz
    - NoSecondPrize
    - ShadowOfTheBeast
    - ShockWave
    - SwordOfSodan
    - Unreal
  - Unreleased:
    - note: Cancelled, unreleased but ultimately recovered games. The list contains both demos and more or less finished games.
    - AlchemyDemo
    - BabylonianTwins
    - Blork
    - DragonsKingdomDemo
    - EvilsDoomDemo
    - HostileBreed
    - Indigo
    - Infection
    - LiquidKids
    - MutantLeagueHockey
    - NoBuddiesLand
    - NuxeliaDemo
    - OperationG2Demo
    - ParadiseLost
    - PuttySquad
    - RaidOverMoscow
    - SnowBros
    - SonShuShi
    - SuperGemZ
    - SuperheroDemo
    - TensaiDemo
    - UniversalMonsters
    - VacSuitJackDemo
    - WhereTimeStoodStill
  - Vector Graphics:
    - note: A sampling of games with wireframe and polygonal graphics.
    - 3DGalax
    - AirSupport
    - Alianator
    - AlphaWaves
    - Archipelagos
    - ATF2
    - CarrierCommand
    - CastleMaster
    - Cybercon3
    - Damocles
    - Eco
    - EmpireStrikesBack
    - Epic
    - Hunter
    - Interphase
    - LightCorridor
    - Mercenary
    - Mercenary3
    - Midwinter
    - NoSecondPrize
    - Resolution101
    - RoboCop3
    - Sentinel
    - Simulcra
    - Starblaze
    - Starglider
    - Starglider2
    - StuntCarRacer
    - Thunderhawk
    - ThunderStrike
    - TotalEclipse
    - TowerOfBabel
    - TrexWarrior
    - Virus
    - Voyager
    - Zeewolf
