- Special Hardware:
  - note: Games with support for special controllers & peripherals, and arcade hardware.
  - image: { ops: { op: "pi", path: "top/peripheral.png" }, size: [320, 128], scale: [1, 1] }
  - Modem or Serial Link:
    - note: Games with local and/or remote multiplayer support.
    - AlienBreed3D2
    - AlienBreed3D
    - ArmourGeddon2
    - ArmourGeddon
    - BattleChess
    - BlueAngels
    - CombatAirPatrol
    - Dominium
    - F16CombatPilot
    - Falcon
    - Fears
    - FighterDuelPro
    - Firepower
    - FlightSimulator2
    - Gloom
    - GravityForce
    - Jet
    - Kikugi
    - KnightsOfTheSky
    - Lotus2
    - MatrixMarauders
    - MaxRally
    - MiG29MSuperFulcrum
    - OverdriveTeam17
    - Populous&DataDisks
    - Populous&DataDisks--TFF
    - Populous&DataDisks--TPL
    - Populous2&ChallengeGames
    - Populous2&ChallengeGames--TCG
    - Powerdrome
    - Powermonger
    - PowermongerWW1Edition
    - Prince
    - RedBaron
    - RoboSport
    - Skidmarks
    - StuntCarRacer
    - SuperSkidmarks+CD
    - Tornado
    - TurboTraxArcane
    - VroomMultiPlayer
    - WildWheels
    - XTremeRacing
  - Light Gun:
    - note: Games with light gun support.\n\n(Not yet available on MiSTer, but most games also feature mouse control.)
    - Aliex
    - Capone
    - CrazyShot
    - Creature
    - CyberAssault
    - DieHard2
    - Enforcer
    - Firestar
    - OperationThunderbolt
    - OperationWolf
    - OrbitalDestroyer
    - POW
    - Sideshow
    - SkeetShoot
    - SpaceGun
    - TakeEmOut
    - WestPhaser
  - Roland MT-32:
    - note: Games with Roland MT-32 MIDI support.
    - CastleOfDrBrainNTSCMT32
    - ConquestsOfTheLongbowMT32
    - KingsQuest5MT32
    - KingsQuestEnhanced--MT32
    - LeisureSuitLarry5MT32
    - LeisureSuitLarryEnhndMT32
    - MixedUpMotherGooseMT32
    - PoliceQuest3NTSCMT32
    - QuestForGlory2MT32
    - SpaceQuest4NTSCMT32
    - SpaceQuestEnhanced--MT32
  - Arcadia Systems:
    - note: Arcadia was an unsuccessful venture by Mastertronic to create an Amiga 500-based multi-game arcade system.
    - MagicJohnsonFstbrkArcadia
    - NinjaMissionArcadia
    - XenonArcadia
    - TableHockeyArcadia
    - SpaceRangerArcadia
    - SideWinderArcadia
    - SpotArcadia
    - TenPinBowlingArcadia
    - DeltaCommandArcadia
    - RoadwarsArcadia
    - PharaohsMatchArcadia
    - BlastaballArcadia
    - UpScopeArcadia
    - Aaargh!Arcadia
    - WorldDartsArcadia
    - WorldTrophySoccerArcadia
    - LeaderBoardArcadia
