- Charts:
  - note: Top games lists compiled or voted by magazines back in the day as well as contemporary outlets.
  - image: { ops: { op: "pi", path: "top/charts.png" }, size: [320, 128], scale: [1, 1] }
  - Amiga Lore Top 100:
    - ordering: "ranked"
    - note: Amiga Lore's aggregate review score ranking, taking into account the largest publications of the era from across the continent. A Metacritic equivalent for the platform, if you will.\n\n(Some duplicate entries exist, since rereleases and CD32 versions are considered separately.)
    - image: { op: "pi", path: "list/amigalore.png" }
    - Populous2&ChallengeGames
    - SWOS9596
    - CannonFodder
    - Lemmings
    - MonkeyIsland2
    - SWOS
    - Flashback
    - Speedball2
    - DesertStrike
    - FireAndIce
    - FirstSamurai
    - FormulaOneGrandPrix
    - Hunter
    - JimmyWhitesSnooker
    - Lemmings2
    - Populous
    - ProjectXSE
    - ThemePark
    - Turrican2
    - ShadowFighter
    - MegaLoMania
    - KickOff2
    - CannonFodderCD32
    - BeneathAStlSky
    - Delphine-Collection: { unavailable: True }
    - DungeonMaster
    - Frontier
    - PinballIllusions
    - Zool
    - SensibleSoccer9293
    - Settlers
    - Speedball2
    - StuntCarRacer
    - SWIV
    - Syndicate
    - IndianaJonesAtlantisAdv
    - Gods
    - Greatest-Collection: { unavailable: True }
    - EyeOfTheBeholder
    - ChaosEngine
    - CruiseForACorpse
    - PuttySquad
    - JamesPond2
    - Lotus
    - PinballIllusions
    - RainbowIslands
    - RoboCop3
    - SecretOfMonkeyIsland
    - AlienBreed2
    - Award-Winners-Gold: { unavailable: True }
    - Banshee
    - BodyBlows
    - Dune2
    - FireAndIce
    - JungleStrike
    - Leander
    - FourCrystalsOfTrazere
    - Lionheart
    - Lotus2
    - Nebulus
    - NoSecondPrize
    - PinballFntsies
    - ProjectX
    - Putty
    - Thunderhawk
    - SensibleSoccerEuro
    - SimCity
    - Starglider2
    - SuperStardust
    - SuprTennisChmps
    - Superfrog
    - OhNoMoreLemmings
    - Goal
    - Gunship2000
    - EyeOfTheBeholder2
    - Civilization
    - AlienBreedSpecialEdition
    - ArcherMacLeansPool
    - Banshee
    - BCKid
    - Deuteros
    - F15StrikeEagle2
    - F19StealthFighter
    - F29Retaliator
    - Falcon
    - Frontier
    - Harlequin
    - LegendOfKyrandia
    - LostVikings
    - PGAEuropeanTour
    - PGATourGolf
    - PinballPrelude
    - Populous
    - ProTennisTour2
    - RailroadTycoon
    - TitusTheFox
    - TowerOfBabel
    - Turrican
    - Xenon2
    - LostTreasuresOfInfocom
  - Amiga Power Top 100 (1991):
    - ordering: "ranked"
    - note: The Top 100 games for the Commodore Amiga according to UK games magazine Amiga Power in 1991.
    - image: { op: "pi", path: "list/amigapower91.jpg" }
    - RainbowIslands
    - Lemmings
    - Speedball2
    - SimCity
    - Virus
    - Populous
    - KickOff2
    - Falcon
    - Indianapolis500
    - StuntCarRacer
    - Pang
    - PrinceOfPersia
    - SpindizzyWorlds
    - Nebulus
    - CarrierCommand
    - DungeonMaster
    - RickDangerous2
    - Ultima5
    - NewZealandStory
    - Sentinel
    - Damocles
    - Paradroid90
    - Plotting
    - TyphoonThompson
    - LaserSquad
    - Klax
    - SWIV
    - IndyJonesLastCrusAdv
    - F19StealthFighter
    - EMotion
    - Captive
    - Powermonger
    - Xenon2
    - Puzznic
    - SuperOffRoad
    - F29Retaliator
    - Vaxine
    - Interphase
    - CastleMaster
    - CarVup
    - SuperHangOn
    - ProTennisTour2
    - Starglider2
    - Shanghai
    - Lotus
    - OperationStealth
    - WCLeaderBoard
    - ArkanoidRevengeOfDoh
    - BattleSquadron
    - TowerOfBabel
    - Wings
    - Cadaver
    - BubbleBobble
    - LeisureSuitLarry3
    - Archipelagos
    - HelterSkelter
    - Bombuzal
    - BattleCommand
    - KillingGameShow
    - IK+
    - Warhead
    - FA18Interceptor
    - FutureWars
    - NightShift
    - Silkworm
    - Midwinter
    - Pacmania
    - KidGloves
    - Projectyle
    - BalanceOfPower1990Ed
    - RickDangerous
    - Loom
    - RocketRanger
    - SaintDragon
    - Elite
    - Quartz
    - Flood
    - BuggyBoy
    - ZanyGolf
    - PipeDream
    - TotalEclipse
    - DragonBreed
    - JamesPond
    - VenusTheFlytrap
    - TetrisMirrorsoft
    - TVSportsFootball
    - DistantArmies
    - Turrican
    - TreasureTrap
    - BatmanTheMovie
    - Switchblade
    - SuperCars
    - TheirFinestHour
    - MiG29Fulcrum
    - MontyPythonsFlyCir
    - GoldenAxe
    - GhoulsNGhosts
    - RedStormRising
    - Xybots
    - GrandMonsterSlam
  - Amiga Power Top 100 (1992):
    - ordering: "ranked"
    - note: The Top 100 games for the Commodore Amiga according to UK games magazine Amiga Power in 1992.
    - image: { op: "pi", path: "list/amigapower92.jpg" }
    - RainbowIslands
    - FormulaOneGrandPrix
    - Speedball2
    - SecretOfMonkeyIsland
    - SimCity
    - MegaLoMania
    - Exile
    - Populous2
    - KnightsOfTheSky
    - JimmyWhitesSnooker
    - Lemmings
    - PrinceOfPersia
    - DynaBlaster
    - FirstSamurai
    - Harlequin
    - PGATourGolf
    - Ultima6
    - ParasolStars
    - EyeOfTheBeholder
    - AnotherWorld
    - F15StrikeEagle2
    - TitusTheFox
    - JohnMaddenFootball
    - Hunter
    - ApidyaKaiko
    - BluesBrothers
    - CelticLegends
    - StuntCarRacer
    - Pang
    - GemX
    - RodLand
    - Switchblade2
    - HeadOverHeels
    - CabaretAsteroids
    - Vroom
    - Nebulus
    - BubbleBobble
    - SWIV
    - RType2
    - IK+
    - Virus
    - Lotus2
    - KickOff&ExtraTime
    - ChuckRock
    - Llamatron
    - Heimdall
    - Realms
    - Klax
    - Shadowlands
    - MicroProseGolf
    - Puzznic
    - SuperOffRoad
    - SuperTwintris
    - CruiseForACorpse
    - LaserSquad
    - Leander
    - Paradroid90
    - Toki
    - Shanghai
    - SpaceCrusade
    - Gods
    - SilentService2
    - PacificIslands
    - FA18Interceptor
    - IndyJonesLastCrusAdv
    - JamesPond2
    - Thunderhawk
    - F29Retaliator
    - NewZealandStory
    - ManchesterUnitedEurope
    - RoboCop3
    - StormMaster
    - Sentinel
    - RugbyTheWorldCup
    - SpindizzyWorlds
    - EMotion
    - Indianapolis500
    - PinballDreams
    - Plotting
    - FinalFight
    - CarrierCommand
    - ProjectX
    - Powermonger
    - Spot
    - ScoobyDoo&ScrappyDoo
    - HeroQuest
    - ProTennisTour2
    - Projectyle
    - TowerOfBabel
    - Volfied
    - KidGloves
    - SuperHangOn
    - SuperCars2
    - CarVup
    - Deuteros
    - PhotonStorm
    - FantasyWorldDizzy
    - MonsterBusiness
    - CovertAction
    - GoldenAxe
  - Amiga Power Top 100 (1993):
    - ordering: "ranked"
    - note: The Top 100 games for the Commodore Amiga according to UK games magazine Amiga Power in 1993.
    - image: { op: "pi", path: "list/amigapower93.jpg" }
    - SensibleSoccer
    - FormulaOneGrandPrix
    - DynaBlaster
    - Speedball2
    - RainbowIslands
    - PinballFntsies
    - Exile
    - Lemmings2
    - KnightsOfTheSky
    - CrazyCars3
    - SimCity
    - Harlequin
    - Apidya
    - ChaosEngine
    - Wizkid
    - GemX
    - MonkeyIsland2
    - ArcherMacLeansPool
    - NoSecondPrize
    - HistoryLine
    - JohnMaddenFootball
    - MegaLoMania
    - IK+
    - LegendsOfValour
    - RType2
    - CabaretAsteroids
    - HeadOverHeels
    - Putty
    - RodLand
    - Populous2
    - BluesBrothers
    - FourCrystalsOfTrazere
    - NickFaldosChampGolf
    - Hunter
    - Vroom
    - Pang
    - LaserSquad
    - Alien3
    - Nebulus
    - Shanghai
    - FirstSamurai
    - ScoobyDoo&ScrappyDoo
    - BillsTomatoGame
    - DGeneration
    - TitusTheFox
    - CurseOfEnchantia
    - LureOfTheTemptress
    - ParasolStars
    - Klax
    - Llamatron
    - PacificIslands
    - Virus
    - BodyBlows
    - PinballDreams
    - Ultima6
    - Projectyle
    - IndianaJonesAtlantisAdv
    - Walker
    - CombatAirPatrol
    - CarrierCommand
    - DarkSeed
    - EMotion
    - AddamsFamily
    - SWIV
    - SuperTwintris
    - ChuckRock2
    - SpindizzyWorlds
    - StuntCarRacer
    - AlienBreedSpecialEdition
    - Anarchy
    - Zool
    - Lotus
    - FireAndIce
    - Lionheart
    - Sentinel
    - Plotting
    - Lemmings
    - MonsterBusiness
    - WorldClassRugby
    - LegendOfKyrandia
    - ATrain
    - Warhead
    - AnotherWorld
    - Striker
    - Puzznic
    - BCKid
    - RType
    - NewZealandStory
    - SuperHangOn
    - Toki
    - SuperOffRoad
    - TearawayThomas
    - RoboCop3
    - KidGloves
    - BugBomber
    - PrinceOfPersia
    - Sleepwalker
    - SpaceCrusade
    - Switchblade2
    - GTSoccerChallenge
  - EAB Top 20 Exclusives:
    - ordering: "ranked"
    - note: The best Amiga-exclusive games according to users of the English Amiga Board.
    - image: { op: "pi", path: "list/eab.png" }
    - Wings
    - WormsDC
    - RuffNTumble
    - Ambermoon
    - Banshee
    - Benefactor
    - DeluxeGalaga
    - Lionheart
    - Napalm: { unavailable: True }
    - WastedDreams
    - Genetic-Species: { unavailable: True }
    - Perihelion
    - ArabianNights
    - Twintris
    - FA18Interceptor
    - K240
    - Apidya
    - Hybris
    - ShadowOfTheBeast3
    - Roadkill
  - Kim Justice Top 100:
    - ordering: "ranked"
    - note: Kim Justice's top 100 Amiga games of all time.
    - image: { op: "pi", path: "list/kimjustice_top100.jpg" }
    - SWOS
    - Syndicate
    - Speedball2
    - ThemePark
    - Civilization
    - Settlers
    - SensibleSoccer
    - PremierManager3
    - LostPatrol
    - ChaosEngine
    - CannonFodder
    - Lemmings
    - Elite
    - BillsTomatoGame
    - WormsDC
    - OneStepBeyond
    - Floor13
    - Lotus2
    - Lemmings2
    - JimmyWhitesSnooker
    - Turrican2
    - Benefactor
    - Populous
    - UltimateSoccerManager
    - Deflektor
    - ArcherMacLeansPool
    - Wings
    - Banshee
    - IK+
    - Wizkid
    - Turrican
    - BalanceOfPower
    - Lionheart
    - DGeneration
    - StuntCarRacer
    - BubbleBobble
    - KillingGameShow
    - Qwak
    - ShadowOfTheBeast
    - ItCameFromTheDesert
    - Walker
    - FootballGlory
    - HeroQuest
    - SimCity
    - KingOfChicago
    - SecondSamurai
    - MoonStone
    - SpaceHulk
    - CannonFodder2
    - ShadowOfTheBeast3
    - PinballDreams
    - Lotus3
    - AlienBreed
    - RodLand
    - Apidya
    - GreatGianaSisters
    - Life&Death
    - BuggyBoy
    - Populous2
    - Zool2
    - NigelMansellsWrldChmp
    - FireAndIce
    - SpaceCrusade
    - MegaLoMania
    - Waxworks
    - Agony
    - ProTennisTour2
    - FirstSamurai
    - AlienBreedTA
    - SpindizzyWorlds
    - WizNLiz
    - ShadowFighter
    - Leander
    - SuperCars2
    - DungeonMaster
    - Premiere
    - ScoobyDoo&ScrappyDoo
    - NoSecondPrize
    - Dune
    - SuperStardust
    - Flood
    - Bombuzal
    - RoboCop3
    - ShufflepuckCafe
    - BattleSquadron
    - Switchblade2
    - Zool
    - RuffNTumble
    - Deuteros
    - SuperSkidmarks
    - BloodMoney
    - BaseJumpers
    - Nebulus
    - Speedball
    - SWIV
    - Virocop
    - VenusTheFlyTrap
    - NavySEALs
    - Uridium2
    - YoJoe
  - Lemon Top 30 (Sep 2022):
    - ordering: "ranked"
    - note: As voted by lemonamiga.com users
    - image: { op: "pi", path: "list/lemon.png" }
    - SecretOfMonkeyIsland
    - MonkeyIsland2
    - Settlers
    - Dune2
    - Turrican2
    - SlamTilt
    - Lemmings
    - SWOS9697
    - Ambermoon
    - CannonFodder
    - Civilization
    - SWOS9596
    - FormulaOneGrandPrix
    - SWOS
    - UFOEnemyUnknown
    - Wings
    - Speedball2
    - SimonTheSorcerer
    - Flashback
    - Syndicate
    - Pirates
    - AnotherWorld
    - PinballFntsies
    - PinballDreams
    - ChaosEngine
    - IndianaJonesAtlantisAdv
    - CannonFodder
    - Lotus2
    - EyeOfTheBeholder2
    - WormsDC
  - Mr Biffo Top 10:
    - note: The 10 best Amiga games according to Mr Biffo of Digitiser 2000.
    - image: { op: "pi", path: "list/digitiser.jpg" }
    - CannonFodder
    - SecretOfMonkeyIsland
    - JamesPond2
    - Lemmings
    - ChaosEngine
    - Worms
    - AlienBreed
    - SensibleSoccer
    - Syndicate
    - JimmyWhitesSnooker
  - retroGAMER A500 Top 10 :
    - note: Top 10 from retroGAMER magazine.
    - image: { op: "pi", path: "list/retrogamer.jpg" }
    - Worms
    - JimmyWhitesSnooker
    - AnotherWorld
    - Lemmings
    - Speedball2
    - SecretOfMonkeyIsland
    - AlienBreed
    - SensibleSoccer
    - ThemePark
    - Wings
