- Multiplayer:
  - note: Lists of games for more than one player.
  - image: { ops: { op: "pi", path: "top/multiplayer.png" }, size: [320, 128], scale: [1, 1] }
  - Best of Multiplayer:
    - note: Our top picks for multiplayer action.
    - BattleIsle
    - ChaosEngine
    - DogsOfWar
    - DynaBlaster
    - HiredGuns
    - Historyline
    - JaguarXJ220
    - Lotus
    - Moonstone
    - Nitro
    - OilImperium
    - Pang
    - PortsOfCall
    - Rampart
    - RodLand
    - SensibleGolf
    - SWOS9596
    - Settlers
    - Silkworm
    - SlamTilt
    - Speedball2
    - SuperCars2
    - SuperSkidmarks+CD
    - SWIV
    - Twintris
    - Worms
  - Competitive:
    - 3DWorldTennis
    - 4DSportsBoxing
    - 4th&Inches
    - ABCMondayNightFB
    - Adrenalynn
    - AdvancedSkiSimulator
    - AdvantageTennis
    - AllanBordersCricket
    - AllTerrainRacing
    - AmericanTagTeamWrestling
    - AmigaKarate
    - Archon2
    - Archon
    - AtomSmasher
    - BadLands
    - Ballistix
    - BangkokKnights
    - BarbarianPalace
    - BattleForAshes
    - BattleIsle&DataDisks
    - BattleIsle&DataDisks--ALSS
    - BattleIsle&DataDisks--Moon
    - BeachVolley
    - BiplaneDuel
    - BladesOfSteel
    - BlastaBallArcadia
    - BlueMax
    - BMXSimulator
    - BodyBlows
    - BodyBlowsGalactic
    - BombX
    - Boppin
    - Botics
    - BrainBlasters
    - BrainMan
    - BrandsHatch
    - BrianLarasCricket
    - BrianLarasCricket96
    - BrutalFootball
    - BrutalHomicide
    - BrutalPawsOfFury
    - Budokan
    - BugBomber
    - BumpNBurn
    - Burnout
    - CapitalPunishment
    - Carnage
    - ChambersOfShaolin
    - Champ
    - CircusAttractions
    - CircusGames
    - Corx
    - Croak
    - Croak2
    - CrossCheck
    - CruncherFactory
    - Cyberball
    - CyberGames
    - DangerousStreets
    - DarkCentury
    - DaysOfThunder
    - Disc
    - Ditris
    - DizzyPanic
    - Dogfight
    - DoubleAgent
    - DoubleDribble
    - DrMario
    - DynaBlaster
    - Ebonstar
    - Elfmania
    - EmlynHughesIntlSoccer
    - EMotion
    - EmpireSoccer94
    - EnglandChampSpecial
    - EskimoGames
    - ETsRugbyLeague
    - EuropeanChampionship1992
    - EuropeanChampionsOcean
    - EuropeanFootballChamp
    - EuroSoccer
    - Extase
    - F1
    - F1WorldChampionshipEd
    - FaceOff
    - FastBreak
    - FIFAInternationalSoccer
    - FightingSoccer
    - FightinSpirit
    - FinalBlow
    - Fire&Forget
    - Firepower
    - FistFighter
    - FullContact
    - FutureBasketball
    - FutureClassicsCollection
    - FutureTank
    - GaryLinekersHotShot
    - GBAChampionshipBB
    - GemStoneLegend
    - Goal
    - GraemeSounessVectorSoccer
    - GrahamGoochSecondInnings
    - GrahamGoochWCCricketSE
    - Gridiron
    - HardBall
    - HardBall2
    - HeartOfTheDragon
    - Historyline
    - HotRod
    - HotRubber
    - Hotshot
    - IanBothamsCricket
    - IK+
    - IndoorSports
    - IndyHeat
    - International3DTennis
    - InternationalIceHockey
    - InternationalSoccer
    - InternationalTennis
    - InternationalTruckRacing
    - IronTrackers
    - Italia1990
    - Italy1990WinnersEdition
    - JaguarXJ220
    - JahangirKhansWChampSquash
    - JohnBarnesEuroFootball
    - JohnMaddenFootball
    - Jouster3
    - JupitersMasterdrive
    - KarateKid2
    - KarateKing&CityDefence
    - KartingGrandPrix
    - KickOff
    - KickOff216
    - KickOff2FinalWhistle
    - KickOff2ReturnToEurope
    - KickOff3
    - Kikstart2
    - Killerball
    - Klax
    - LabyrinthDetNyeCOMputerDk
    - LamborghiniAmericanChllng
    - LastDuel
    - Lemmings
    - Limes&Napoleon
    - Loopz
    - LordsOfWar
    - Lotus
    - Lotus2
    - Lotus3
    - MagicJohnsonsBasketball
    - ManchesterUnited
    - ManchesterUnitedEurope
    - ManchesterUnitedTheDouble
    - ManchesterUnitedPLC
    - Manix
    - MarbleMadness
    - MasterAxe
    - MasterBlaster
    - Masterblazer
    - MatrixMarauders
    - MaxRally
    - MegaBlast
    - MetalMasters
    - MicroMachines
    - MicroProseSoccer
    - MikroMortalTennis
    - Mindbender
    - MinskiesAGA
    - Moonstone
    - MortalKombat
    - MortalKombat2
    - MrMenOlympics
    - MUDS
    - Nitro
    - NoExit
    - NorthAndSouth
    - OhNoMoreLemmings
    - Oktagon
    - OneOnOne
    - OperationCombat2
    - OrientalGames
    - OverTheNet
    - PanzaKickBoxing
    - PassingShot
    - PeterBeardsleysIF
    - PharaohsMatchArcadia
    - PitFighter
    - PlayerManager2Extra
    - Plotting
    - Pod
    - Pong
    - PrimalRage
    - ProBoxingSimulator
    - Projectyle
    - ProPowerBoatSimulator
    - ProSoccer2190
    - ProTennisSimulator
    - RallyCrossChallenge
    - Rampart
    - RBI2Baseball
    - Ringside
    - RiseOfTheRobots
    - RoadWarsArcadia
    - RockChallenge
    - RoketzAGA
    - RugbyTheWorldCup
    - Rushhour
    - SalmonPinkMax
    - SensibleSoccer
    - SensibleSoccer9293
    - SensibleSoccerBulldogBlty
    - SensibleSoccerIntEd
    - SensibleWorldMoonSoccer
    - SWOSv11
    - SWOS9596
    - SWOS9697
    - SWOS9596ECE
    - SWOS98
    - Settlers
    - ShadowFighter
    - ShadowWarriors
    - SierraSoccer
    - Skidmarks
    - SkiOrDie
    - SkyChase
    - Sliders
    - Sneech
    - Spaceball
    - Speedball2
    - Speedball
    - SpittingImage
    - SpyVsSpy
    - SpyVsSpy2TheIslandCaper
    - SpyVsSpy3ArcticAntics
    - StarControl
    - Stormball
    - StreetFighter
    - StreetFighter2
    - StreetRacer
    - StreetSportsBB
    - Striker
    - Subtrade
    - SuperCars2
    - SuperGrandPrix
    - SuperLoopz
    - SuperOffRoad
    - SuperOsWALD
    - SuperSkidmarks
    - SuperstarIceHockey
    - SuperStreetFighter2
    - SuperTwintris
    - SuprStrtFtr2Trbo
    - SuprTennisChmps
    - TableHockeyArcadia
    - TableTennisSimulation
    - Taekwondo
    - TanksFurry
    - TennisChamps
    - TennisCup1Mb
    - TennisCup2
    - Tetrix
    - ThomasTheTankEngine2
    - TieBreak
    - TimeLock
    - TipOff
    - TomLandryFootballDeluxe
    - Toobin
    - TopGear2
    - TotalFootball
    - Traders
    - TubeWarriors
    - Turbo
    - TurboRaketti2Fi
    - TurnNBurn
    - TVSportsBaseball
    - TVSportsBasketball
    - TVSportsBoxing
    - TVSportsFootball
    - Twintris
    - TwinTurbos
    - UltimateRide
    - Vectorball
    - VictoryRoad
    - Vindicators
    - WayneGretzkyHockey
    - WayneGretzkyHockey2
    - WayOfTheLittleDragon
    - WembleyIntSoccer
    - WembleyRugbyLeague
    - WesternGames
    - WildCupSoccer
    - WorldChampionshipSoccer
    - WorldClassRugby
    - WorldClassRugby5Nations
    - WorldClassRugby95
    - WorldClassSoccer
    - WorldCup90
    - WorldTrophySoccerArcadia
    - Wormsigns
    - WWFEuropeanRampageTour
    - WWFWrestleMania
    - ZeroGravity
    - Zoom
    - Zyconix
  - Cooperative:
    - Alcatraz
    - AlienBreed2
    - AlienBreedSpecialEdition
    - AlienBreedTA
    - AlienStorm
    - AlienSyndrome
    - AlloAllo
    - AlphaWaves
    - AlteredBeast
    - ApidyaKaiko
    - ApidyaSpecialEdition
    - Area88
    - AuntArcticAdventure
    - AztecChallenge
    - BadCompany
    - BadDudes
    - Bagitman
    - Banshee
    - BaseJumpers
    - BattleSquadron
    - Battletoads
    - BeastBusters
    - BetterDeadThanAlien
    - BlackShadow
    - Blasteroids
    - BlockShock
    - BloodMoney
    - Bloodwych
    - BluesBrothers
    - BonanzaBros
    - BridesOfDracula
    - BubbleBobble
    - Cabal
    - CaptainFizz
    - Carcharodon
    - ChaosEngine
    - ChaosEngine2
    - CJInTheUSA
    - CJsElephantAntics
    - CoolCrocTwins
    - Crack
    - Crackdown
    - CrazySeasons
    - Cyberblast
    - Cyberzerk
    - DalekAttack
    - Datastorm
    - DeathMaskAGA
    - DeathTrap
    - Deep
    - DeluxeGalaga
    - DinoWars
    - DogsOfWar
    - DonkTheSamuraiDuck
    - DoubleDragon
    - DoubleDragon2
    - DoubleDragon3
    - DynamiteDux
    - DynastyWars
    - EmeraldMine
    - EmeraldMine2
    - EmeraldMine3
    - Enemy2MissingInAction
    - EnemyTempestOfViolence
    - Enlightenment
    - EscapeRobotMonsters
    - ESWAT
    - Exterminator
    - FinalFight
    - Flipit&Magnose
    - ForgottenMine
    - ForgottenWorlds
    - Frenetic
    - Garrison
    - Garrison2
    - Gauntlet2
    - Gauntlet3
    - GeminiWing
    - GoldenAxe
    - HeavyMetalHeroes
    - HellRaisers
    - HelterSkelter
    - HiredGuns
    - IkariWarriors
    - Joe&MacCavemanNinja
    - Kamikaze
    - Leatherneck
    - LethalXcess
    - LineOfFire
    - Llamatron
    - LupoAlberto
    - MegaTwins
    - Mercs
    - MidnightResistance
    - Moochies
    - Narc
    - NaughtyOnes
    - NewYorkWarriors
    - NinjaWarriors
    - Oath
    - OoopsUp
    - OperationThunderbolt
    - OverdriveInfacto
    - P47Thunderbolt
    - Pang
    - ParasolStars
    - Phobia
    - PipeDream
    - Pixie&Dixie
    - POW
    - Power
    - PrehistoricTale
    - Qwak
    - Rampage
    - RealGhostbusters
    - RealPopeye
    - Rebellion
    - Renegades
    - RevengeOfMutantCamels
    - RodLand
    - RollerCoasterRumbler
    - ScrambleSpirits
    - SecondSamurai
    - Silkworm
    - SkeletonKrew
    - Skull&Crossbones
    - Slackskin&Flint
    - SmashTV
    - Sooty&Sweep
    - SpaceGun
    - SpaceTaxi3
    - SpellBound
    - Spherical
    - Starush
    - SuperCFast
    - SuperMethaneBros
    - SuperSkweek
    - SuperSpaceInvaders
    - SWIV
    - SwordsOfTwilight
    - TeenageMtntHeroTurtlesCOp
    - Terminator2Arcade
    - ThunderJaws
    - TimeBandit
    - TinyTroops
    - TommyGun
    - TotalCarnage
    - Transplant
    - Troddlers
    - TubularWorlds
    - Ugh
    - UNSquadron
    - Uridium2
    - Virocop
    - WarZoneCoreDesign
    - Watchtower
    - Wizball
    - WizNLiz
    - Xenex
    - Xenophobe
    - Xybots
    - YoJoe
    - ZOut
  - Modem or Serial Link:
    - AlienBreed3D2
    - AlienBreed3D
    - ArmourGeddon2
    - ArmourGeddon
    - BattleChess
    - BlueAngels
    - CombatAirPatrol
    - Dominium
    - F16CombatPilot
    - Falcon
    - Fears
    - FighterDuelPro
    - Firepower
    - FlightSimulator2
    - Gloom
    - GravityForce
    - Jet
    - Kikugi
    - KnightsOfTheSky
    - Lotus2
    - MatrixMarauders
    - MaxRally
    - MiG29MSuperFulcrum
    - OverdriveTeam17
    - Populous&DataDisks
    - Populous&DataDisks--TFF
    - Populous&DataDisks--TPL
    - Populous2&ChallengeGames
    - Populous2&ChallengeGames--TCG
    - Powerdrome
    - Powermonger
    - PowermongerWW1Edition
    - Prince
    - RedBaron
    - RoboSport
    - Skidmarks
    - StuntCarRacer
    - SuperSkidmarks+CD
    - Tornado
    - TurboTraxArcane
    - VroomMultiPlayer
    - WildWheels
    - XTremeRacing
  - Taking Turns:
    - "1869"
    - 3DPool
    - 7Colors
    - AmericanGladiators
    - Antago
    - AquaticGames
    - ArcadePool
    - ArcadeSnooker
    - ArcadeTriviaQuiz
    - ArcherMacLeansPool
    - Arena
    - ArtOfChess
    - BadCat
    - BalanceOfPower1990Ed
    - BallGame
    - BanditKings
    - BarGames
    - BattleChess
    - BattleChess2
    - Battleships
    - Betrayal
    - BigBusiness
    - BlackGoldReLINE
    - Bobo
    - BuffaloBillsWildWestShow
    - Burntime
    - CaliforniaGames
    - CaliforniaGames2
    - CarlLewisChallenge
    - CastleWarrior
    - CelticLegends
    - Chessmaster2000
    - Chessmaster2100
    - ChessPlayer2150
    - ChessSimulator
    - ClassicBoardGames
    - ClueMasterDetective
    - ColossusChessX
    - ComputerScrabble
    - ComputerThirdReich
    - CyberEmpires
    - DDayImpressions
    - DecimalDungeon
    - Detroit
    - DistantArmies
    - DragonsBreath
    - ElectronicPool
    - Eye
    - FeudalLords
    - FiendishFreddysBigTopOFun
    - FractionAction
    - FullMetalPlanete
    - GamesSummerEdition
    - GamesWinterEdition
    - Gettysburg
    - GlobalTrek
    - HeroQuest2
    - Hilt2
    - HoleInOne&DataDisks
    - Infection
    - IntSportsChallenge
    - Ishido
    - JimmyWhitesSnooker
    - JockyWilsonsDartChallenge
    - JohnLowesUltimateDarts
    - Kingpin
    - LaserSquad
    - LeaderBoard
    - LeaderBoardArcadia
    - LeaderBoardTD1
    - LegendOfRagnarok
    - Links&DataDisks
    - LordsOfChaos
    - LordsOfTheRealm
    - MathWizard
    - MickeysMemoryChallenge
    - MicroProseGolf
    - MikeReadsComputerPopQuiz
    - MiniGolf
    - MultiPlayerSoccerManager
    - NickFaldosChampGolf
    - Obsession
    - Ogre
    - OilImperium
    - Patrician
    - PGAEuropeanTour
    - PGATourGolf
    - PinballDreams
    - PinballFntsies
    - PinballIllusions
    - PinballMagic
    - PinballMania
    - PinballWizard
    - PlayerManager2
    - Pool
    - PortsOfCall
    - PowerPinball
    - Powerplay
    - PremierManager
    - PremierManager2
    - PremierManager3Deluxe
    - PubTriviaSimulator
    - Quadrel
    - QuestionOfSport
    - QuiksilverPinball
    - Read&Rhyme
    - RedLightning
    - Revelation
    - Risk
    - RoboSport
    - RunTheGauntlet
    - Saint&Greavsie
    - Scrabble
    - SensibleGolf
    - Shanghai
    - SlamTilt
    - SpaceCrusade&VoyageBeyond
    - SteelEmpire
    - Subbuteo
    - SummerGames
    - SummerGames2
    - SummerOlympiad
    - Tangram
    - TenPinBowlingArcadia
    - ThomasTankEngPinball
    - TimeScanner
    - TournamentGolf
    - TrianGO
    - TrivialPursuit
    - TrivialPursuitANB
    - UltimateGolf
    - UniversalMilitarySim
    - VoyagesOfDiscovery
    - WackyDarts
    - Warlords
    - Waterloo
    - WCLeaderBoard
    - WhiteDeath
    - WildWestWorld
    - WinterGames
    - WinterOlympiad88
    - WinterOlympics
    - WinterSupersports92
    - Winzer
    - WorldGames
    - WorldTourGolf
    - Worms
    - WormsDC
    - ZanyGolf
