- PocketAdditions:
  - hidden: true
  - AdventuresOfWillyBeamish
  - AxelsMagicHammer
  - BackToTheFuturePart2
  - BackToTheFuturePart3
  - BartVsSpaceMutants
  - BartVsTheWorld
  - BigNoseTheCaveman
  - Bill&TedsExcellentAdv
  - BombJack
  - BubbleDizzy
  - ChampionshipManager93
  - ChampionshipManager94-ESE
  - ChaseHQ
  - ChaseHQ2
  - ChipsChallenge
  - ChuckieEgg
  - ChuckieEgg2
  - CoolSpot
  - DaleyThompsonsOC
  - DizzyPrinceOfTheYolkFolk
  - CountDuckula
  - CountDuckula2
  - EmpireStrikesBack
  - GhostBusters2
  - GhostsNGoblins
  - GhoulsNGhosts
  - JungleBook
  - KidGloves
  - KidGloves2
  - LicenceToKill
  - LionKing
  - LittlePuffInDragonland
  - McDonaldLand
  - ReturnOfTheJedi
  - RoboCop
  - RoboCop2
  - RollingThunder
  - SeymourGoesToHollywood
  - SpellboundDizzy
  - StarWars
  - SWOS2223
  - TeenageMtntHeroTurtles
  - TeenageMtntHeroTurtlesCOP
  - TeenageMtntNinjaTurtles
  - Terminator2JudgmentDay
  - ThunderBlade
  - Vyper
