- PocketAdditions:
  - hidden: true
  - AdventuresOfWillyBeamish
  - AgeOfRock
  - AnotherWorldLostLevel
  - ApidyaSpecialEdition
  - Area88
  - AxelsMagicHammer
  - BackToTheFuturePart2
  - BackToTheFuturePart3
  - BartVsSpaceMutants
  - BartVsTheWorld
  - BigNoseTheCaveman
  - Bill&TedsExcellentAdv
  - BomberBob
  - BombJack
  - BombJackBeerEdition
  - BoneCruncherEnhanced
  - Boxx4
  - BridgeStrike
  - BubbleDizzy
  - ChampionshipManager93
  - ChampionshipManager94-ESE
  - ChaseHQ
  - ChaseHQ2
  - ChipsChallenge
  - ChuckieEgg
  - ChuckieEgg2
  - CoolSpot
  - CountDuckula
  - CountDuckula2
  - DaleyThompsonsOC
  - DizzyPrinceOfTheYolkFolk
  - EmpireStrikesBack
  - EyeOfTheBeholder2AGA
  - EyeOfTheBeholderAGA
  - FlyingSharkSE
  - GhostBusters2
  - GhostsNGoblins
  - GhoulsNGhosts
  - Giana2
  - GreenBeret
  - HighSeasTraderAGA
  - HongKongPhooey
  - JungleBook
  - Karateka
  - KickOff2CV
  - KidGloves
  - KidGloves2
  - KingsValley
  - KnightmareKonami
  - LemmingsNewYear9192
  - LicenceToKill
  - LionKing
  - LittlePuffInDragonland
  - LumberJackRevision
  - MariaRenardsRevenge
  - MarvinsMarvellousAdvAGA
  - McDonaldLand
  - MetalGear
  - MetroCross
  - MoreLemmings
  - Motorhead
  - Mousetrap
  - PersianGulfInferno
  - Pong4b
  - PowerGlove
  - PPHammer
  - Prehistorik
  - ProjectXSE2017
  - PuttySquadAGA
  - RaidOverMoscow
  - ReshootR
  - ReturnOfTheJedi
  - RickDangerousAGA
  - RoboCop
  - RoboCop2
  - RogueDeclanZero
  - RollingThunder
  - Rotator
  - RygarAGA
  - SeymourGoesToHollywood
  - SkillGrid
  - SolidGold
  - SolomonsKey2
  - SpaceTaxi3
  - SpellboundDizzy
  - Starquake
  - StarWars
  - Stormlord
  - StuntCarRacerTNT
  - SuperCars2AGA
  - SuperSprint
  - SWOS1617
  - SWOS2020
  - SWOS2021
  - SWOS2122
  - SWOS2223
  - TanksFurry
  - Tapper
  - TeenageMtntHeroTurtles
  - TeenageMtntHeroTurtlesCOP
  - TeenageMtntNinjaTurtles
  - Terminator2JudgmentDay
  - TerrysBigAdventure
  - TestDrive2&DataDisksNGC
  - ThunderBlade
  - TigerClaw
  - TinyBobble
  - TinyGalaga
  - TinyInvaders
  - Tinyus
  - Tony&Friends
  - TrackerHeroAGA
  - TurboSprint
  - Turrican2AGA
  - UntouchablesSE
  - Vyper
  - WoodysWorld
  - Worthy
  - WrongWayDriver
  - XeviousAGA
  - ZGRED
